accounts/urls.py
from django.conf.urls import url,include
from django.contrib.auth.views import  login,logout
from accounts import views





urlpatterns = [
    url(r'^$',views.register, name='register'),
    url(r'^registro/sucesso/$' ,views.success_register, name='success_register'),
    url(r'^ativar/(?P<token>\w+)/$',views.user_active, name='user_active'),
    url(r'^recuperar/$',views.recover_account, name='recover_account'),
    url(r'^recuperar/(?P<id>\d+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.create_new_password, name='create_new_password'),
    url(r'^inclui_usuario',views.register_viewer,name='register_viewer'),
    url(r'^altera_usuario/(?P<pk>\d+)',views.edit_viewer,name='edit_viewer'),
    url(r'^reset_password/(?P<pk>\d+)',views.reset_password,name='reset_password')


]

nilusweb/nilusnfs/urls.py
from django.conf.urls import url,include
from nilusnfs import views


urlpatterns = [
    # Listagens dos cadastros
    url(r'^pnfs/$',views.paramnfs_list,name='paramnfs_list'),
    url(r'^insere_parametros/$', views.create_paramnfs, name='create_paramnfs'),
    url(r'^insere_parametros/(?P<pk>\d+)$', views.edit_paramnfs, name='edit_paramnfs'),
    url(r'^paramnfs/(?P<pk>\d+)/apagar/$', views.delete_paramnfs, name='delete_paramnfs'),
    url(r'^faturamento/$',views.fat_list,name='fat_list'),
    url(r'^notasemitidas/$',views.nfs_list,name='nfs_list'),
    url(r'^notasemitidas/atualiza/(?P<pk>\d+)$',views.refresh_nfs,name='refresh_nfs'),
    url(r'^notasemitidas/info/(?P<pk>\d+)$', views.info_nfs, name='info_nfs'),
    url(r'^notasemitidas/cancela/(?P<pk>\d+)$',views.cancel_nfs,name='cancel_nfs')
]

nilusweb/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import login
from core import views
from django.contrib.auth.views import logout
from django.conf.urls.static import  static
from django.conf import settings

urlpatterns = [
    url(r'^$',login,{'template_name' : 'signin.html'}, name='signin'),
    url(r'^conta/', include('accounts.urls')),
    url(r'^principal/', include('principal.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^sair/$', logout, {'next_page': 'signin'}, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nilusnfs/forms.py
from django import forms
from niluscad.models import Company,Cadgeral
from nilusnfs.models import Paramnfs,TmpFat
from niluscad.models import PlanoFinan
from nilusfin.models import Contafinanceira


class FormCreateParamnfs(forms.ModelForm):

    def __init__(self, user, *args, **kwargs):
        super(FormCreateParamnfs, self).__init__(*args, **kwargs)
        self.fields['company'].queryset = Company.objects.filter(master_user=user.user_master)
        self.fields['company'].empty_label = 'Selecione uma empresa'
        self.fields['regime_trib'].empty_label = 'Informe o regime'

    class Meta:
        model = Paramnfs

        fields = ['company','cd_srv_padrao','desc_srv', 'aliquota_iss','cnae','it_lista_srv', 'simples_nac', 'incent_cult','regime_trib',
                  'certificado_pfx','certificado_nome','certificado_senha','conf_sequenciaNFE','conf_serieNFE',
                  'conf_sequencialoteNFe','conf_usuarioAcesso','conf_senhaUsuarioAcesso','conf_enviaEmail']




class FiltroBuscaFaturamento(forms.Form):


    prox_fat_ini = forms.DateField(label='Ultimo Faturamento de:', required=False)
    prox_fat_fim = forms.DateField(label='Ultimo Faturamento até:', required=False)

    empresa = forms.ModelChoiceField(label='Empresa', required=False, empty_label='Todas',
                                     queryset=Company.objects.none())
    cadgeral = forms.ModelChoiceField(label='Cliente / Fornecedor', empty_label='Todos', required=False,
                                      queryset=Cadgeral.objects.none())

    lista_os = forms.BooleanField(label='listar O.S', required=False)

    def __init__(self, empresa, cliente, *args, **kwargs):
        super(FiltroBuscaFaturamento, self).__init__(*args, **kwargs)
        self.fields['empresa'].queryset = empresa
        self.fields['cadgeral'].queryset = cliente






class FormFaturamento(forms.Form):

    ids_fat = forms.ModelMultipleChoiceField(queryset=TmpFat.objects.none())
    data_fat = forms.DateField(required=False)

    plano_financeiro = forms.ModelChoiceField(label="Plano Financeiro", empty_label='Escolha o plano', required=True,
                                              queryset=PlanoFinan.objects.none())

    conta_financeira = forms.ModelChoiceField(label="Conta Recebimento", empty_label='Escolha a conta', required=True,
                                              queryset=Contafinanceira.objects.none())

    fatura_unificado = forms.BooleanField(label='Faturamento Agrupado',required=False)


    def __init__(self,lista_fat,planofinan,contafinan,*args, **kwargs):
        super(FormFaturamento, self).__init__(*args, **kwargs)
        self.fields['ids_fat'].queryset = lista_fat
        self.fields['plano_financeiro'].queryset = planofinan
        self.fields['conta_financeira'].queryset = contafinan





class FiltroBuscaNotas(forms.Form):


    dt_emissao_ini = forms.DateField(label='Emissão de:', required=False)
    dt_emissao_fim = forms.DateField(label='Emissão até:', required=False)

    empresa = forms.ModelChoiceField(label='Empresa', required=False, empty_label='Todas',
                                     queryset=Company.objects.none())
    cadgeral = forms.ModelChoiceField(label='Cliente / Fornecedor', empty_label='Todos', required=False,
                                      queryset=Cadgeral.objects.none())


    def __init__(self, empresa, cliente, *args, **kwargs):
        super(FiltroBuscaNotas, self).__init__(*args, **kwargs)
        self.fields['empresa'].queryset = empresa
        self.fields['cadgeral'].queryset = cliente

nilusnfs/views.py
from threading import Thread
from django.http import HttpResponse,Http404
from datetime import date, timedelta, datetime
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView,TemplateView,UpdateView,FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from .models import Paramnfs,TmpFat
from .forms import FormCreateParamnfs,FiltroBuscaFaturamento,FormFaturamento,FiltroBuscaNotas
from nilusadm.models import Sequenciais
from nilusfin.models import Contafinanceira
from niluscad.models import Company,Cadgeral,PlanoFinan
from niluscont.servicos import cria_lancamento_credito,cria_lancamento_credito_unificado,fat
from nilusnfs.models import NotasFiscais
from django.db.models import Q
from .enotas_util import cad_empresa_emissora,edit_empresa_emissora,refresh_situacao_nfs,cancela_nfs



@login_required
def paramnfs_list(request):

   if request.is_ajax():
        template_name = '_table_paramnfs.html'
   else:
       template_name = 'paramnfs_list.html'

   paramnfs = Paramnfs.objects.filter(master_user=request.user.user_master)
   pendencias_cad = []
   for p in paramnfs:
        if not p.company.fantasia or\
            not p.company.insc_mun or\
                not p.company.endereco or\
                    not p.company.endereco or\
                        not p.company.cidade or\
                            not p.company.uf or\
                                not p.company.cep or\
                                    not p.company.bairro:
                                        pendencias_cad.append({'pk_empresa': p.company.pk })



   context = {
      'paramnfs' : paramnfs,
      'pendencias' : pendencias_cad
   }

   return render(request, template_name,context)





class CreateParamNFS(LoginRequiredMixin,CreateView):
    def get_template_names(self):
        return ["create_paramnfs.html"]

    def get_context_data(self, **kwargs):
        context = super(CreateParamNFS, self).get_context_data(**kwargs)
        return context

    def get_form_kwargs(self):
        kwargs = super(CreateParamNFS, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs




    model = Paramnfs
    form_class = FormCreateParamnfs


    def get_success_url(self):
        return reverse_lazy('paramnfs_list')


    def form_valid(self,form):
        paramnfs = form.save(commit=False)
        paramnfs.master_user = self.request.user.user_master
        seq_paramnfs = Sequenciais.objects.get(user=self.request.user.user_master)


        paramnfs.num_param = seq_paramnfs.paramnfs + 1
        seq_paramnfs.paramnfs = paramnfs.num_param
        seq_paramnfs.save()

        cad_empresa_emissora(paramnfs)
        paramnfs.save()

        return redirect(self.get_success_url())




class EditParamNFS(LoginRequiredMixin,UpdateView):

    def get_template_names(self):
       return ["edit_paramnfs.html"]

    def get_success_url(self):
        return reverse_lazy('paramnfs_list')

    def get_form_kwargs(self):
        kwargs = super(EditParamNFS, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


    def get_context_data(self, **kwargs):
        context = super(EditParamNFS, self).get_context_data(**kwargs)
        context['dados_cadastro'] = Paramnfs.objects.get(pk=self.kwargs['pk'])
        return context

    model = Paramnfs
    form_class = FormCreateParamnfs

    def form_valid(self,form):
        paramnfs = form.save(commit=False)

        edit_empresa_emissora(paramnfs)
        form.save()

        return redirect(self.get_success_url())


@login_required
def delete_paramnfs(request, pk):
    paramnfs = get_object_or_404(Paramnfs,master_user=request.user.user_master,pk=pk)
    try:
       paramnfs.delete()
    except:
       print('erro na exclusao')

    return redirect('paramnfs_list')



# ######################################################################################################
#               FATURAMENTO E EMISSÃO DE NOTAS DE SERVIÇOS                                             #
########################################################################################################

@login_required
def fat_list(request):

    if request.is_ajax():
        template_name = '_table_faturamento.html'
    else:
        template_name = 'fat_list.html'

    filtrou = 'nao'
    data_hoje = datetime.today

    lista_fat = TmpFat.objects.filter(master_user=request.user.user_master,tipo='C',situacao=False)
    empresa = Company.objects.filter(master_user=request.user.user_master)
    cadgeral = Cadgeral.objects.filter(master_user=request.user.user_master)
    planofinan = PlanoFinan.objects.filter(master_user=request.user.user_master,sinal='R')
    contafinan = Contafinanceira.objects.filter(master_user=request.user.user_master,conta_recebimento=True)



    form = FiltroBuscaFaturamento(empresa,cadgeral,request.GET or None)




    if form.is_valid():
        prox_fat_ini = form.cleaned_data.get('prox_fat_ini', '')
        prox_fat_fim = form.cleaned_data.get('prox_fat_fim', '')
        empresa = form.cleaned_data.get('empresa', '')
        cadgeral = form.cleaned_data.get('cadgeral', '')
        lista_os = form.cleaned_data.get('lista_os','')




        if lista_os:
            lista_fat = TmpFat.objects.filter(master_user=request.user.user_master, situacao=False)
            filtrou = 'ok'

        if prox_fat_ini:
            lista_fat = lista_fat.filter(data_fat__gte=prox_fat_ini)
            filtrou = 'ok'

        if prox_fat_fim:
            lista_fat = lista_fat.filter(data_fat__lt=prox_fat_fim+timedelta(days=1))
            filtrou = 'ok'

        if empresa:
            lista_fat = lista_fat.filter(Q(contrato__company=empresa) | Q(os__company=empresa))
            filtrou = 'ok'

        if cadgeral:
            lista_fat = lista_fat.filter(Q(contrato__cadgeral=cadgeral) | Q(os__cadgeral=cadgeral))
            filtrou = 'ok'





    form_fat = FormFaturamento(lista_fat,planofinan,contafinan,request.POST or None)
    if form_fat.is_valid():
        plano_financeiro = form_fat.cleaned_data['plano_financeiro']
        # fat_unificado = form_fat.cleaned_data['fatura_unificado']
        faturar = form_fat.cleaned_data['ids_fat']
        data_fat = form_fat.cleaned_data['data_fat']
        contafinan = form_fat.cleaned_data['conta_financeira']
        if data_fat is None:
            data_fat = datetime.now()




        faturamento = Thread(target=fat,
                     args=[faturar, plano_financeiro, data_fat, contafinan])
        faturamento.start()
        # else:
        #
        #         retorno_unificado = cria_lancamento_credito_unificado(faturar,plano_financeiro,data_fat,contafinan)



    context = {
        'lista': lista_fat,
        'form' : form,
        'filtrou' : filtrou,
        'data_hoje' : data_hoje,
        'form_fat': form_fat,
    }
    return render(request, template_name, context)




# ######################################################################################################
#               NOTAS FISCAIS EMITIDAS                                                                 #
########################################################################################################

@login_required
def nfs_list(request):

    if request.is_ajax():
        template_name = '_table_nfs.html'
    else:
        template_name = 'nfs_list.html'

    filtrou = 'nao'
    data_hoje = datetime.today

    notas = NotasFiscais.objects.filter(master_user=request.user.user_master).order_by('-data_emissao')
    empresa = Company.objects.filter(master_user=request.user.user_master)
    cadgeral = Cadgeral.objects.filter(master_user=request.user.user_master)

    notas_pendentes = NotasFiscais.objects.filter(master_user=request.user.user_master,
                                                  envio_concluido='N')
    # print(notas_pendentes)

    refresh_notas = Thread(target=refresh_situacao_nfs,
                           args=[notas_pendentes])
    refresh_notas.start()

    form = FiltroBuscaNotas(empresa,cadgeral,request.GET or None)

    if form.is_valid():
        dt_emissao_ini = form.cleaned_data.get('dt_emissao_ini', '')
        dt_emissao_fim = form.cleaned_data.get('dt_emissao_fim', '')
        empresa = form.cleaned_data.get('empresa', '')
        cadgeral = form.cleaned_data.get('cadgeral', '')





        if dt_emissao_ini:
            notas = notas.filter(data_emissao__gte=dt_emissao_ini)
            filtrou = 'ok'

        if dt_emissao_fim:
            notas = notas.filter(data_emissao__lt=dt_emissao_fim+timedelta(days=1))
            filtrou = 'ok'

        if empresa:
            notas = notas.filter(company=empresa)
            filtrou = 'ok'

        if cadgeral:
            notas = notas.filter(cadgeral=cadgeral)
            filtrou = 'ok'


        notas = notas.order_by('-data_emissao')





    context = {
        'notas': notas,
        'form' : form,
        'filtrou' : filtrou,
        'data_hoje' : data_hoje,
    }
    return render(request, template_name, context)



@login_required
def refresh_nfs(request, pk):
    nfs = NotasFiscais.objects.filter(master_user=request.user.user_master,pk=pk)
    refresh_situacao_nfs(nfs)

    return redirect('nfs_list')



@login_required
def info_nfs(request,pk):

    if request.is_ajax():
        template_name = '_info_nfs.html'
    else:
        raise Http404

    nf = NotasFiscais.objects.get(pk=pk)

    context = {
        'nf': nf,
    }

    return render(request, template_name, context)


@login_required
def cancel_nfs(request,pk):

    nf = NotasFiscais.objects.get(master_user=request.user.user_master,pk=pk)
    cancela_nfs(nf)

    return redirect('nfs_list')



















create_paramnfs =  CreateParamNFS.as_view()
edit_paramnfs = EditParamNFS.as_view()

nilusnfs/templates/_edit_paramnfs.html
{% load static widget_tweaks %}
{% if success %}
   <script>
  	 close_modal=true;
  	 ok = true;
   </script>
{% else %}

{% endif %}

nilusnfs/templates/_table_itensfat.html
        <table id="table_faturamento" class="table table-bordered table-striped table-vcenter js-dataTable-full" >
            <thead>
                <tr>
                    <th><small>Faturar</small></th>
                    <th><small>Nº</small></th>
                    <th><small>Tipo</small></th>
                    <th><small>Cliente</small></th>
                    <th><small>Serviço</small></th>
                    <th><small>Dt Fat/OS</small></th>
                    <th><small>Valor</small></th>
                </tr>
            </thead>
            <tbody>
            {% for l in lista %}
                    <td>
                        <center><label class="custom-control custom-checkbox baixa_lancamento">
                                                <input type="checkbox" class="custom-control-input baixa_lancamento" name="ids_fat" value="{{ l.pk }}">
                                                  <span class="custom-control-indicator"></span>
                                                <span class="custom-control-description"></span>
                        </label></center>
                    <!--<center><input class="baixa_lancamento"  name="lanc_baixa" value="{{ lanc.pk }}" type="checkbox"></center>-->
                    </td>
                    <td><small>{% if l.tipo == 'O' %} {{ l.os.num_os }} {% else %} {{ l.contrato.num_cont }} {% endif %}</small></td>
                    <td>{% if l.tipo == 'C' %} <span class="badge badge-primary" text="Contrato">CONTRATO</span>
                                          {% else %} <span class="badge badge-info" text="O.S">O.S</span>
                                          {% endif %}
                    </td>
                    <td><small><strong>{% if l.tipo == 'O' %} {{ l.os.cadgeral }} {% else %} {{ l.contrato.cadgeral }} {% endif %}</strong></small></td>
                    <td><small>{% if l.tipo == 'O' %} {{ l.os.desc_item }} {% else %} {{ l.contrato.item }} {% endif %}</small></td>
                    <td><small>{% if l.tipo == 'O' %} {{ l.os.data_os|date:'d/m/Y' }} {% else %} {{ l.contrato.prox_faturamento|date:'d/m/Y' }} {% endif %}</small></td>
                    <td><span>{% if l.tipo == 'O' %} {{ l.os.valor_unit }} {% else %} {{ l.contrato.valor }} {% endif %}</span></td>
                </tr>

            {% endfor %}
            </tbody>
        </table>

nilusnfs/templates/_table_paramnfs.html
    <table id="tabela_paramnfs" class="table table-bordered table-striped table-vcenter js-dataTable-full">
                <thead>
                    <tr>
                        <th style="width:10%;">Código</th>
                        <th style="width:70%;">Empresa</th>
                        <th style="width:20%;"></th>
                    </tr>
                </thead>
                <tbody>
                {% for p in paramnfs %}
                    <tr>
                        <td>{{ p.num_param }}</td>
                        <td>{{ p.company }}</td>
                        <td>
                            {% for pend in pendencias  %}
                              {% if p.company.pk == pend.pk_empresa %}
                                    <button type="button" class="btn btn-sm btn-warning pendencias_cad"  href="{% url 'edit_company' pend.pk_empresa %}" data-toggle="tooltip" data-placement="bottom" title="Empresa com pendências/Clique para atualizar o cadastro">
                                        <i class="fa fa-warning"></i>
                                    </button>
                              {% endif %}
                            {% endfor %}
                             <a  class="btn btn-sm btn-outline-secondary edit_paramnfs"  href="{% url 'edit_paramnfs' p.pk  %}" data-toggle="tooltip" data-placement="bottom" title="Editar">
                                <i class="fa fa-pencil"></i>
                             </a>
                             <button type="button" class="btn btn-sm btn-outline-danger delete_paramnfs"  href="{% url 'delete_paramnfs' p.pk %}" data-toggle="tooltip" data-placement="bottom" title="Excluir">
                                <i class="fa fa-trash-o"></i>
                             </button>

                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

nilusnfs/templates/fat_list.html
{% extends "menu.html" %}
{% load static widget_tweaks humanize utils %}



<!-- Bread crumb and right sidebar toggle -->
{% block title %} Faturamento de Serviços {% endblock %}

{% block page_body %}
<div class="block">
    <div class="block-content">
        <div class="block">
            <div class="block-content block-content-full ribbon ribbon-left ribbon-bookmark ribbon-primary">
                <button class="btn btn-outline-info mr-5 mb-5 baixa btn_lancamentos pull-right"
                        data-toggle="tooltip" data-placement="bottom" title="Baixar Selecionados"  title="Pagar / Receber Lancamentos Selecionados"
                         id="btn_faturar"><i class="fa fa-check-circle"></i></button>
                <button type="button"  class="btn  btn-outline-primary btn_lancamentos  mr-5 mb-5" id="mostrar_filtros"   data-toggle="tooltip" data-placement="bottom" title="Exibir filtros de pesquisa">
                   <i class="fa fa-filter"></i> Pesquisar
               </button>

                <div class="ribbon-box form_busca" style="display:none;">
                    Filtros de Pesquisa
                </div>
                <input type="hidden" name="info_delete_vinculado" id="info_delete_vinculado" value="0">

                <br>

                <br>
                <div class="form_busca" style="display:none;">
                    <form>
                        <div class="filtros_extras">
                            <div class="row">
                                <div class="col-md-8">

                                        <div class="form-material input-group">
                                            <label>{{ form.empresa.label_tag }}</label>
                                            {% render_field form.empresa class="chosen-select" %}
                                        </div>

                                </div>
                                <div class="col-md-4">
                                    <div class="mt-20">
                                        <label class="css-control css-control-sm css-control-primary css-switch">
                                            {% render_field form.lista_os type="checkbox" class='css-control-input' %}
                                            <span class="css-control-indicator"></span> Listar O.S's?
                                    </label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-material input-group">
                                        <label>{{ form.cadgeral.label_tag }}</label>
                                        {% render_field form.cadgeral class="chosen-select" %}
                                    </div>
                                </div>
                                <div class="col-4">
                                    <label for="id_prox_fat_ini">Data de Emissão/Faturamento:</label>
                                    <div class="input-daterange input-group js-datepicker-enabled" data-date-format="dd/mm/yyyy" data-week-start="1" data-autoclose="true" data-today-highlight="true">
                                        {% render_field form.prox_fat_ini class="form-control js-datepicker"   placeholder="dd/mm/aaaa" data-week-start="1" data-autoclose="true" data-today-highlight="true"%}
                                        <span class="input-group-addon font-w600">  &nbsp; até  &nbsp; </span>
                                        {% render_field form.prox_fat_fim class="form-control js-datepicker"   placeholder="dd/mm/aaaa" data-week-start="1" data-autoclose="true" data-today-highlight="true"%}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-material input-group">
                                        <button type="submit"  class="btn  btn-outline-primary mr-5 mb-5 form_pesquisa form_bus"   data-toggle="tooltip" data-placement="bottom" title="Pesquisar">
                                            <i class="fa fa-search"></i>
                                        </button>
                                        <button type="button"  class="btn  btn-outline-danger  mr-5 mb-5 limpa_filtro_pesquisa_fat"   data-toggle="tooltip" data-placement="bottom" title="Remover filtros">
                                             <i class="fa fa-search-minus"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div>
                    <div class="row">
                        <div class="form_inc col-md-12">
                        </div>
                        <div class="form_inc_despesa col-md-12">
                        </div>
                    </div>
                    <div class="row">
                        <div class="form_edit col-md-12"></div>
                    </div>
                </div>
            </div>
                <div class="row table table_os_contratos">
                 <form method="post" action="" id="form_fat">
                     <div>
                        <input type="hidden"  name="data_fat" id="data_fat">
                        <input type="hidden"  name="plano_financeiro" id="plano_financeiro">
                        <input type="hidden"  name="conta_financeira" id="conta_financeira">
                        <input type="hidden"  name="fatura_unificado" id="fatura_unificado">
                     </div>

                     {% csrf_token %}
                     {% include '_table_itensfat.html' %}
                 </form>
                </div>
            </div>
        </div>
    </div>
</div>



{% include 'modais_lancfin.html' %}


<div class="modal fade" id="modal-databaixa" tabindex="-1" role="dialog" aria-labelledby="modal-slideright" aria-hidden="true">
    <div class="modal-dialog modal-dialog-slideright modal-sm " role="document">
        <div class="modal-content">
            <div class="block block-themed block-transparent mb-0">
                <div class="block-header bg-primary-dark">
                    <h3 class="block-title titulo_modal">Faturar selecionados.</h3>
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
                            <i class="si si-close"></i>
                        </button>
                    </div>
                </div>
                <div class="block-content">
                    <div class="form-material input-group">
                      <label>Data do Faturamento</label>
                      <input  type="text"  name="data_fat_modal" id="data_fat_modal" class="js-datepicker form-control"
                              data-week-start="1" data-autoclose="true" data-today-highlight="true"
                              data-date-format="dd/mm/yyyy" placeholder="dd/mm/aaaa" value="{{ data_hoje|date:'d/m/Y'  }}">
                    </div>
                    <div class="row">
                        <div class="form-material input-group">
                        <label>{{ form_fat.plano_financeiro.label_tag }}</label>
                        {% render_field form_fat.plano_financeiro class="chosen-select" %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-material input-group">
                        <label>{{ form_fat.conta_financeira.label_tag }}</label>
                        {% render_field form_fat.conta_financeira class="chosen-select" %}
                        </div>
                    </div>
                    <div class="form-material input-group" hidden>
                        <label class="css-control css-control-sm css-control-primary css-switch">
                                <input type="checkbox" class='css-control-input' id="id_fatura_unificado" name="fatura_unificado">
                                <span class="css-control-indicator"></span>Agrupa faturamento por cliente?
                         </label>
                    </div>
                    <br>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-alt-primary" id="confirma_fatura" data-dismiss="modal">OK</button>
                <button type="button" class="btn btn-alt-secondary" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>





{% endblock %}


{% block javascript %}

$('.form_inc').hide();
$('.form_edit').hide();
$('.chosen-select').chosen({ width: '100%' });

{% include 'js_filtros_pesquisas.html' %}

table = $('#table_faturamento').DataTable({
    "language": {
     "lengthMenu": "Mostrando _MENU_ registros por página",
     "search" : "Procurar: ",
     "info" : "Exibindo de _START_ a _END_ de _TOTAL_ registros",
     "infoEmpty": "Nenhum registro encontrado",
     "infoFiltered": "(filtrado entre _MAX_ registros)",
     "paginate" : {
       "first":      "Primeiro",
       "last":       "Último",
       "next":       "Próximo",
       "previous":   "Anterior"
     },
     responsive: {
            details: {
                type: 'column'
            }
        },
        columnDefs: [ {
            className: 'control',
            orderable: false,
            targets:   0
        } ],
        order: [ 1, 'asc' ]
 }
});

$("#confirma_fatura").on("click",function(e){

    var fat_uni = $('#id_fatura_unificado').val();
    $('#fatura_unificado').val(fat_uni);

    var data = $('#data_fat_modal').val();
    $('#data_fat').val(data);

    var plr_finan = $('#id_plano_financeiro').val()
    $('#plano_financeiro').val(plr_finan);

    var conta_fin = $('#id_conta_financeira').val()
    $('#conta_financeira').val(conta_fin);

    var fat_uni= $('#id_fatura_unificado').val()
    $('#fatura_unificado').val(fat_uni);

    $('#form_fat').submit();
});



$("#btn_faturar").on("click",function(e){
    if($('.baixa_lancamento').is(":checked")){
        $('#modal-databaixa').modal("show");

    }else{
       swal('Atenção', 'Nenhum registro selecionado!', 'warning');
    }
});


{% endblock %}