accounts/urls.py
from django.conf.urls import url,include
from django.contrib.auth.views import  login,logout
from accounts import views





urlpatterns = [
    url(r'^$',views.register, name='register'),
    url(r'^registro/sucesso/$' ,views.success_register, name='success_register'),
    url(r'^ativar/(?P<token>\w+)/$',views.user_active, name='user_active'),
    url(r'^recuperar/$',views.recover_account, name='recover_account'),
    url(r'^recuperar/(?P<id>\d+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.create_new_password, name='create_new_password'),
    url(r'^inclui_usuario',views.register_viewer,name='register_viewer'),
    url(r'^altera_usuario/(?P<pk>\d+)',views.edit_viewer,name='edit_viewer'),
    url(r'^reset_password/(?P<pk>\d+)',views.reset_password,name='reset_password')


]

lancfinanceiros/urls.py
from django.conf.urls import url, include
from nilusfin import views
from lancfinanceiros import views

urlpatterns = [

    url(r'^$', views.lancfin_list, name='lancfin_list'),
    url(r'^lancamentos/baixas',views.baixfin_list,name='baixfin_list'),
    url(r'^lancamentos/info/(?P<pk>\d+)$',views.infoLanctos,name='infoLanctos'),

    url(r'^insere_receita$',views.create_receita,name='create_receita'),
    url(r'^insere_despesa$',views.create_despesa,name='create_despesa'),
    url(r'^insere_receita/(?P<pk>\d+)$', views.edit_receita, name='edit_receita'),
    url(r'^insere_despesa/(?P<pk>\d+)$', views.edit_despesa, name='edit_despesa'),
    url(r'^lancamento/(?P<pk>\d+)/apagar/$', views.delete_receita, name='delete_receita'),
    url(r'^lancamento/(?P<pk>\d+)/apagar_vinculado/$', views.delete_lancto_vinculado, name='delete_lancto_vinculado'),
    url(r'^lancamentos/baixap/(?P<pk>\d+)$',views.baixa_parcial,name='baixa_parcial'),
    url(r'^movimentacoes/exclui/(?P<pk>\d+)$',views.exclui_movimentacao,name='exclui_movimentacao'),

    # url(r'^fin/lanc/baixas', include('nilusfin.urls')),
    # url(r'^despesa/(?P<pk>\d+)/apagar/$', views.delete_despesa, name='delete_despesa'),


]

nilusweb/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import login
from core import views
from django.contrib.auth.views import logout
from django.conf.urls.static import  static
from django.conf import settings

urlpatterns = [
    url(r'^$',login,{'template_name' : 'signin.html'}, name='signin'),
    url(r'^conta/', include('accounts.urls')),
    url(r'^principal/', include('principal.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^sair/$', logout, {'next_page': 'signin'}, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lancfinanceiros/models.py
from django.db import models

# Create your models here.


class Lancamentos(models.Model):
    # informação do dono da conta (usuario Master)
    master_user = models.ForeignKey('accounts.User',models.CASCADE,verbose_name='Usuario Master')

    # dados principais (empresa e numero do lançamento)
    num_lan = models.IntegerField('Nº Registro')
    parcela = models.IntegerField('Parcela',default=1)
    company = models.ForeignKey('niluscad.Company',models.PROTECT,verbose_name='Empresa')


    #dados do titulo
    cadgeral = models.ForeignKey('niluscad.CadGeral',models.PROTECT,verbose_name='Cliente',blank=True,null=True)
    dt_lancamento = models.DateField('Data Lançamento',null=True,blank=True)
    dt_vencimento = models.DateField('Data Vencimento',null=True,blank=True)
    plr_financeiro = models.ForeignKey('niluscad.Planofinan',models.PROTECT,verbose_name='Plano Financeiro')
    conta_finan = models.ForeignKey('nilusfin.Contafinanceira',models.PROTECT,verbose_name='Conta Recebimento')
    c_custo = models.ForeignKey('niluscad.Ccusto',models.PROTECT,verbose_name='Centro de Custo',blank=True,null=True)
    vlr_lancamento = models.DecimalField('Valor do Lançamento',max_digits=13,decimal_places=2,blank=True,null=True)
    valor_text = models.CharField(verbose_name='Valor',  max_length=20)
    saldo = models.DecimalField('Saldo', max_digits=13,decimal_places=2,blank=True,null=True)
    descricao = models.CharField(verbose_name='Observação', max_length=200,null=True,blank=True)
    titulo = models.BooleanField('É Titulo', default=False)

    #Dados Cotação/Indice
    indice = models.ForeignKey('nilusfin.Indice',models.PROTECT,null=True,blank=True)
    cotacao = models.ForeignKey('nilusfin.Cotacao',models.PROTECT,null=True,blank=True)

    situacao = models.BooleanField('Baixado',default=False)
    reaberto = models.BooleanField('Reaberto',default=False)
    data_baixa = models.DateField('Data de Recebimento',null=True,blank=True)
    lancamento_pai = models.ForeignKey('self',models.SET_NULL,blank=True,null=True,verbose_name='Lançamento Pai')

    # Dados Baixa e Situação
    tipoLancto_Choices = (
        ('R', 'Receita'),
        ('D', 'Despesa'),
    )
    tipo_lancamento = models.CharField('Tipo', max_length=1, choices=tipoLancto_Choices)

    def verifica_parcela(self):
        if self.lancamento_pai:
            return True
        return Lancamentos.objects.filter(lancamento_pai=self).exists()


    def altera_parcelas(self,confirma_parcela,alterado):
        if confirma_parcela == 'T':
            if self.lancamento_pai:
                parcelas = Lancamentos.objects.filter(
                    models.Q(lancamento_pai=self.lancamento_pai) | models.Q(pk=self.lancamento_pai.pk)
                )
                for a in alterado:
                    if a == 'situacao':
                        situacao_new = a
                        parcelas.update(situacao=self.situacao)
                        if self.situacao == True:
                            parcelas.update(data_baixa=self.data_baixa)
                    else:
                        situacao_new = 'N'

                parcelas.update(
                    plr_financeiro=self.plr_financeiro,c_custo=self.c_custo,valor_text=self.valor_text,
                    vlr_lancamento = self.vlr_lancamento,indice=self.indice,cotacao=self.cotacao,
                    descricao=self.descricao,saldo=self.saldo,cadgeral=self.cadgeral

                )
                for p in parcelas:
                    movto_lanc = Movtos_lancamentos.objects.get(lancamento=p, tipo_movto='C')
                    movto_lanc.vlr_movimento = p.vlr_lancamento
                    movto_lanc.company = p.company
                    movto_lanc.save()
                    if situacao_new == 'situacao':
                        if p.situacao == True:
                            movto_lanc_del = Movtos_lancamentos.objects.get(lancamento=p,tipo_movto='B')
                            movto_lanc_del.delete()

                            movto_lanc = Movtos_lancamentos()
                            movto_lanc.company = p.company
                            movto_lanc.lancamento = p
                            movto_lanc.dt_movimento = p.dt_baixa
                            movto_lanc.vlr_movimento = p.saldo
                            if p.tipo_lancamento == 'R':
                                movto_lanc.desc_movimento = 'Recebido'
                            else:
                                movto_lanc.desc_movimento = 'Pago'
                            movto_lanc.tipo_movto = 'B'
                            movto_lanc.save()
            else:
                parcelas = Lancamentos.objects.filter(lancamento_pai = self)

                for a in alterado:
                    if a == 'situacao':
                        situacao_new = a
                        parcelas.update(situacao=self.situacao)
                        if self.situacao == True:
                            parcelas.update(data_baixa=self.data_baixa)
                    else:
                        situacao_new = 'N'


                parcelas.update(
                    plr_financeiro=self.plr_financeiro, c_custo=self.c_custo,valor_text=self.valor_text,
                    vlr_lancamento=self.vlr_lancamento, indice=self.indice, cotacao=self.cotacao,
                    descricao=self.descricao,saldo=self.saldo,cadgeral=self.cadgeral
                )
                for p in parcelas:
                    movto_lanc = Movtos_lancamentos.objects.get(lancamento=p, tipo_movto='C')
                    movto_lanc.vlr_movimento = p.vlr_lancamento
                    movto_lanc.company = p.company
                    movto_lanc.save()
                    if situacao_new == 'situacao':
                        if p.situacao == True:
                            movto_lanc_del = Movtos_lancamentos.objects.filter(lancamento=p, tipo_movto='B')
                            movto_lanc_del.delete()

                            movto_lanc = Movtos_lancamentos()
                            movto_lanc.company = p.company
                            movto_lanc.lancamento = p
                            movto_lanc.dt_movimento = p.data_baixa
                            movto_lanc.vlr_movimento = p.saldo
                            if p.tipo_lancamento == 'R':
                                movto_lanc.desc_movimento = 'Recebido'
                            else:
                                movto_lanc.desc_movimento = 'Pago'
                            movto_lanc.tipo_movto = 'B'
                            movto_lanc.save()
                        else:
                            movto_lanc_del = Movtos_lancamentos.objects.filter(lancamento=p, tipo_movto='B')
                            movto_lanc_del.delete()

        elif confirma_parcela == 'P':
            if self.lancamento_pai:
                parcelas = Lancamentos.objects.filter(
                    models.Q(lancamento_pai=self.lancamento_pai) | models.Q(pk=self.lancamento_pai.pk,situacao=False)
                )

                for a in alterado:
                    if a == 'situacao':
                        situacao_new = a
                        parcelas.update(situacao=self.situacao)
                        if self.situacao == True:
                            parcelas.update(data_baixa=self.data_baixa)
                    else:
                        situacao_new = 'N'

                parcelas.update(
                    plr_financeiro=self.plr_financeiro,c_custo=self.c_custo,valor_text=self.valor_text,
                    vlr_lancamento = self.vlr_lancamento,indice=self.indice,cotacao=self.cotacao,
                    descricao=self.descricao,saldo=self.saldo,cadgeral=self.cadgeral
                )
                for p in parcelas:
                    movto_lanc = Movtos_lancamentos.objects.get(lancamento=p, tipo_movto='C')
                    movto_lanc.vlr_movimento = p.vlr_lancamento
                    movto_lanc.company = p.company
                    movto_lanc.save()
                    if situacao_new == 'situacao':
                        if p.situacao == True:
                            movto_lanc_del = Movtos_lancamentos.objects.get(lancamento=p,tipo_movto='B')
                            movto_lanc_del.delete()

                            movto_lanc = Movtos_lancamentos()
                            movto_lanc.company = p.company
                            movto_lanc.lancamento = p
                            movto_lanc.dt_movimento = p.dt_baixa
                            movto_lanc.vlr_movimento = p.saldo
                            if p.tipo_lancamento == 'R':
                                movto_lanc.desc_movimento = 'Recebido'
                            else:
                                movto_lanc.desc_movimento = 'Pago'
                            movto_lanc.tipo_movto = 'B'
                            movto_lanc.save()
            else:
                parcelas = Lancamentos.objects.filter(situacao=False,lancamento_pai=self)

                for a in alterado:
                    if a == 'situacao':
                        situacao_new = a
                        parcelas.update(situacao=self.situacao)
                        if self.situacao == True:
                            parcelas.update(data_baixa=self.data_baixa)
                    else:
                        situacao_new = 'N'


                parcelas.update(
                    plr_financeiro=self.plr_financeiro, c_custo=self.c_custo,valor_text=self.valor_text,
                    vlr_lancamento=self.vlr_lancamento, indice=self.indice, cotacao=self.cotacao,
                    descricao=self.descricao,saldo=self.saldo,cadgeral=self.cadgeral
                )
                for p in parcelas:
                    movto_lanc = Movtos_lancamentos.objects.get(lancamento=p, tipo_movto='C')
                    movto_lanc.vlr_movimento = p.vlr_lancamento

lancfinanceiros/templates/_select_cotacao.html
{% load l10n humanize %}
{% for cot in cotacao %}
    <option value="{{ cot.pk|unlocalize }}">{{ cot.valor_cotacao_text|intcomma }} - {{ cot.data_indice|date:'d/m/Y' }}</option>
{% endfor %}

lancfinanceiros/templates/_select_cotacao2.html
{% load l10n static widget_tweaks humanize %}
{{  valor_cotacao }}

lancfinanceiros/templates/js_edicao_lancamentos.html
$(".table_lancfinanceiro").on("click", ".edit_lancto",function(e){
    e.preventDefault();
    $(".form_edit ").load($(this).attr('href'), function(){
          $('.form_edit').show("slide");
          $('.form_busca').hide("drop");
          $('.table_lancfinanceiro').hide("drop");
          $('.btn_lancamentos').hide("drop");

           $(".js-datepicker").datepicker({
            todayBtn: true,
            language: "pt-BR",
            autoclose: true,
            todayHighlight: true
        });


          {% include 'js_floating_labels.html' %}
          {% include 'js_masks.html' %}
          {% include 'js_tabs.html' %}
          {% include 'js_tabelas_formularios.html' %}
          {% include 'js_inclusoes.html' %}

          $('.chosen-select').chosen({ width: '100%' });

          if ( $.fn.dataTable.isDataTable( '#tabela_movimentacoes' ) ) {
               table = $('#tabela_movimentacoes').DataTable();
          }
          else {
                table = $('#tabela_movimentacoes').DataTable( {
                pageLength: 4,
                autoWidth: false,
                searching: false,
                "language": {
                    "lengthMenu": "Mostrando _MENU_ registros por página",
                    "search" : "Procurar: ",
                    "info" : "Exibindo de _START_ a _END_ de _TOTAL_ registros",
                    "infoEmpty": "Nenhum registro encontrado",
                    "infoFiltered": "(filtrado entre _MAX_ registros)",
                    "paginate" : {
                        "first":      "Primeiro",
                        "last":       "Último",
                        "next":       "Próximo",
                        "previous":   "Anterior"
                },
                responsive: {
                    details: {
                        type: 'column'
                    }
                },
                columnDefs: [ {
                    className: 'control',
                    orderable: false,
                    targets:   0
                } ],
                order: [ 1, 'asc' ]},

                dom: "<'row'<'col-sm-12'tr>>" +
                    "<'row'<'col-sm-6'i><'col-sm-6'p>>"

          });
}



          $('.form_edit #id_vlr_text').focus();


          function load_cotacaoform(){
            var indice_id = $('#id_indice').val();
            if(indice_id != ''){
                var url = '{% url 'indice_cotacao' %}';
                url = url+'?indice_id='+indice_id;
                 $("#id_cotacao").load(url,function(){
                $("#id_cotacao").trigger("chosen:updated");
                });
            }
            else{
                $("#id_cotacao").html('');
            }
        }


        $("#id_indice").on("change",function(e){
               load_cotacaoform();
        });





        $('#id_situacao').click(function() {
            if($(this).is(':checked'))
                var marcado = true;

            else{
                   if(confirm("Ao desmarcar este status, todas as baixas deste lançamento serão excluidas, deseja continuar?")){
                    $(this).prop("checked", false);
                   }
                   else{
                       $(this).prop("checked", true);
                   }
            }
        });


          $(".form_edit .cancel_form").on("click",function(e){
              $('.form_edit').hide("drop");
              $('.table_lancfinanceiro').show("puff");
              $('.btn_lancamentos').show("puff");
              $('#tabela_movimentacoes').remove();

          });
    });


});


$(".form_edit").on("submit","form",function(e){
	 	 e.preventDefault();

	 	 var dados = $(this).serialize();
	 	 $.post($(this).attr('action'),dados,function(result){
	 	    $(".form_edit").html(result);
                window.location.reload();
	 	 });
	 });

lancfinanceiros/templates/js_filtros_pesquisas.html
$("#mostrar_filtros").on("click",function(e){
  $(this).hide();
  $('.form_busca').show();
});

var filtrou
filtrou = '{{ filtrou }}';

if(filtrou == 'ok'){
  $('#mostrar_filtros').hide();
  $('.form_busca').show();
}


$(".limpa_filtro_pesquisa").on("click",function(e){
   window.location="{% url 'nfs_list' %}"
});



$(".limpa_filtro_pesquisa_contratos").on("click",function(e){
   window.location="{% url 'contratos_list' %}"
});



$(".limpa_filtro_pesquisa_os").on("click",function(e){
   window.location="{% url 'os_list' %}"
});


$(".limpa_filtro_pesquisa_fat").on("click",function(e){
   window.location="{% url 'fat_list' %}"
});

lancfinanceiros/templates/js_inclui_despesa.html
$(".new_despesa").on("click",function(e){
     e.preventDefault();
     $(".form_inc_despesa").load("{% url 'create_despesa' %}", function(){
        $('.form_inc_despesa').show("puff");
        $('.form_busca').hide("drop");
        $('.table_lancfinanceiro').hide("drop");
        $('.btn_lancamentos').hide("drop");
        $('.e_titulo').hide();
        $('.parcelamento').hide();
        $("#id_valor_text").focus();

        $('.chosen-select').chosen({ width: '100%' });

        {% include 'js_floating_labels.html' %}
        {% include 'js_tabs.html' %}
        {% include 'js_masks.html' %}
        {% include 'js_inclusoes.html' %}


        $(".form_inc_despesa").on("change", "#id_titulo", function(e){
			if ($(this).is(":checked")){
				$(".e_titulo").show();
                $("#id_repetir").prop("checked",false)
                $(".repetir").hide();
			}
			else {
				$(".e_titulo").hide();
			}
		 });

        $(".form_inc_despesa").on("change", "#id_parcela", function(e){
			if ($(this).is(":checked")){
				$(".parcelamento").show();
                $("#id_repetir").prop("checked",false)
                $("#id_dt_vencimento").prop('required',true);
                $(".repetir").hide();

                $("#id_dias_entre_vencto").keyup(function() {
                    if($(this).val().length > 0){
                         $("#id_dia_fixo").prop('disabled',true);
                    }
                    else{
                         $("#id_dia_fixo").prop('disabled',false);
                    }
                });

                $(".form_inc_despesa").on("change", "#id_dia_fixo", function(e){
                    if ($(this).is(":checked")){
                        $("#id_dias_entre_vencto").prop('disabled',true);
                    }
                    else {
                        $("#id_dias_entre_vencto").prop('disabled',false);
                    }
                });

			}
			else {
				$(".parcelamento").hide();
			}
		});

        $(".form_inc_despesa").on("change", "#id_repetir", function(e){
			if ($(this).is(":checked")){
				$(".repetir").show();
                $("#id_parcela").prop("checked",false)
                $(".parcelamento").hide();
                $("#id_dt_vencimento").prop('required',true);
                $("#id_qtd_repetir").prop('required',true);
			}
			else {
				$(".repetir").hide();
                $("#id_dt_vencimento").prop('required',false);
                $("#id_qtd_repetir").prop('required',false);
			}
		 });


        $(".js-datepicker").datepicker({
            todayBtn: true,
            language: "pt-BR",
            autoclose: true,
            todayHighlight: true
        });


        function load_cotacaoform(){
            var indice_id = $('#id_indice').val();
            if(indice_id != ''){
                var url = '{% url 'indice_cotacao' %}';
                url = url+'?indice_id='+indice_id;
                 $("#id_cotacao").load(url,function(){
                $("#id_cotacao").trigger("chosen:updated");
                });
            }
            else{
                $("#id_cotacao").html('');
            }
        }

        $("#id_indice").on("change",function(e){
               load_cotacaoform();
        });
              load_cotacaoform();



          $(".form_inc_despesa .cancel_form").on("click",function(e){
            $('.form_inc_despesa').hide("drop");
            $('.table_lancfinanceiro').show("puff");
            $('.btn_lancamentos').show("puff");
          });

        $('#btn_salvar').on("click",function(e){
            var cpo_empresa
            var cpo_plr_finan
            var cpo_ccusto
            var cpo_contafin
            var alerta = 'n'

            cpo_empresa = $('#id_company').val();
            cpo_plr_finan = $('#id_plr_financeiro').val();
            cpo_ccusto  = $('#c_custo_id2').val();
            cpo_contafin = $('#id_conta_finan2').val();


            if(cpo_plr_finan == ''){
                if(alerta == 'n'){
                alert ('Favor preencher os campos obigatórios!');
                }
                alerta = 's';
                $('.aviso_plr_financeiro').show();
            }

            if(cpo_empresa == ''){
                if(alerta == 'n'){
                alert ('Favor preencher os campos obigatórios!');
                }
                alerta = 's';
                $('.aviso_company').show();
            }

            if(cpo_ccusto == ''){
                if(alerta == 'n'){
                alert ('Favor preencher os campos obigatórios!');
                }
                alerta = 's';
                $('.aviso_ccusto').show();
            }

            if(cpo_contafin == ''){
                if(alerta == 'n'){
                alert ('Favor preencher os campos obigatórios!');
                }
                alerta = 's';
                $('.aviso_conta_finan').show();
            }


            if((cpo_plr_finan == '') || (cpo_empresa == '') || (cpo_ccusto == '')
               (cpo_contafin == '')) {
                    if(alerta == 'n'){
                        alert ('Favor preencher os campos obigatórios!');
                    }
                    if (cpo_plr_finan == ''){
                    $('.aviso_plr_financeiro').show();
                    }
                    if (cpo_empresa == ''){
                    $('.aviso_company').show();
                    }
                    if (cpo_ccusto == ''){
                    $('.aviso_ccusto').show();
                    }
                    if (cpo_contafin == ''){
                    $('.aviso_conta_finan').show();
                    }
            }
        });

    });
});


$(".form_inc_despesa").on("submit","form",function(e){
     e.preventDefault();
     var dados = $(this).serialize();
     $.post("{% url 'create_despesa' %}",dados,function(result){
        $(".form_inc").html(result);
        if(close_modal==true){
           $('.form_inc').hide("drop");
           $('.table_lancfinanceiro').show("puff");
           $('.btn_lancamentos').show();
           window.location.reload();
        }
        else{
            $(".form_inc_despesa").show();
            {% include 'js_floating_labels.html' %}
            {% include 'js_tabs.html' %}
            $('.chosen-select').chosen({ width: '100%' });

            $(".form_inc .cancel_form").on("click",function(e){
                 $('.form_inc').hide("drop");
                 $('.table_lancfinanceiro').hide("drop");
                 $('.btn_lancamentos').show();
            });
        }
     });
});

lancfinanceiros/templates/js_inclui_receita.html
$(".new_receita").on("click",function(e){
     e.preventDefault();
     $(".form_inc").load("{% url 'create_receita' %}", function(){
        $('.form_inc').show("puff");

        $('.form_busca').hide("drop");
        $('.table_lancfinanceiro').hide("drop");
        $('.btn_lancamentos').hide("drop");
        $('.e_titulo').hide();
        $('.parcelamento').hide();
        $("#id_valor_text").focus();

        $('.chosen-select').chosen({ width: '100%' });

        {% include 'js_floating_labels.html' %}
        {% include 'js_tabs.html' %}
        {% include 'js_masks.html' %}
        {% include 'js_inclusoes.html' %}


        $(".form_inc").on("change", "#id_titulo", function(e){
			if ($(this).is(":checked")){
				$(".e_titulo").show();
                $("#id_repetir").prop("checked",false)
                $(".repetir").hide();
			}
			else {
				$(".e_titulo").hide();
			}
		 });

        $(".form_inc").on("change", "#id_parcela", function(e){
			if ($(this).is(":checked")){
				$(".parcelamento").show();
                $("#id_repetir").prop("checked",false)
                $("#id_dt_vencimento").prop('required',true);
                $(".repetir").hide();

                $("#id_dias_entre_vencto").keyup(function() {
                    if($(this).val().length > 0){
                         $("#id_dia_fixo").prop('disabled',true);
                    }
                    else{
                         $("#id_dia_fixo").prop('disabled',false);
                    }
                });

                $(".form_inc").on("change", "#id_dia_fixo", function(e){
                    if ($(this).is(":checked")){
                        $("#id_dias_entre_vencto").prop('disabled',true);
                    }
                    else {
                        $("#id_dias_entre_vencto").prop('disabled',false);
                    }
                });

			}
			else {
				$(".parcelamento").hide();
			}
		});

        $(".form_inc").on("change", "#id_repetir", function(e){
			if ($(this).is(":checked")){
				$(".repetir").show();
                $("#id_parcela").prop("checked",false)
                $(".parcelamento").hide();
                $("#id_dt_vencimento").prop('required',true);
                $("#id_qtd_repetir").prop('required',true);



			}
			else {
				$(".repetir").hide();
                $("#id_dt_vencimento").prop('required',false);
                $("#id_qtd_repetir").prop('required',false);
			}
		 });


        $(".js-datepicker").datepicker({
            todayBtn: true,
            language: "pt-BR",
            autoclose: true,
            todayHighlight: true
        });


        function load_cotacaoform(){
            var indice_id = $('#id_indice').val();
            if(indice_id != ''){
                var url = '{% url 'indice_cotacao' %}';
                url = url+'?indice_id='+indice_id;
                 $("#id_cotacao").load(url,function(){
                $("#id_cotacao").trigger("chosen:updated");
                });
            }
            else{
                $("#id_cotacao").html('');
            }
        }


        $("#id_indice").on("change",function(e){
               load_cotacaoform();
        });
              load_cotacaoform();


          $(".form_inc .cancel_form").on("click",function(e){
            $('.form_inc').hide("drop");
            $('.table_lancfinanceiro').show("puff");
            $('.btn_lancamentos').show("puff");

          });


        $('#btn_salvar').on("click",function(e){
            var cpo_empresa
            var cpo_plr_finan
            var cpo_ccusto
            var cpo_contafin
            var alerta = 'n'

            cpo_empresa = $('#id_company').val();
            cpo_plr_finan = $('#id_plr_financeiro').val();
            cpo_ccusto  = $('#c_custo_id2').val();
            cpo_contafin = $('#id_conta_finan2').val();


            if(cpo_plr_finan == ''){
                if(alerta == 'n'){
                alert ('Favor preencher os campos obigatórios!');
                }
                alerta = 's';
                $('.aviso_plr_financeiro').show();
            }

            if(cpo_empresa == ''){
                if(alerta == 'n'){
                alert ('Favor preencher os campos obigatórios!');
                }
                alerta = 's';
                $('.aviso_company').show();
            }

            if(cpo_ccusto == ''){
                if(alerta == 'n'){
                alert ('Favor preencher os campos obigatórios!');
                }
                alerta = 's';
                $('.aviso_ccusto').show();
            }

            if(cpo_contafin == ''){
                if(alerta == 'n'){
                alert ('Favor preencher os campos obigatórios!');
                }
                alerta = 's';
                $('.aviso_conta_finan').show();
            }


            if((cpo_plr_finan == '') || (cpo_empresa == '') || (cpo_ccusto == '')
               (cpo_contafin == '')) {
                    if(alerta == 'n'){
                        alert ('Favor preencher os campos obigatórios!');
                    }
                    if (cpo_plr_finan == ''){
                    $('.aviso_plr_financeiro').show();
                    }
                    if (cpo_empresa == ''){
                    $('.aviso_company').show();
                    }
                    if (cpo_ccusto == ''){
                    $('.aviso_ccusto').show();
                    }
                    if (cpo_contafin == ''){
                    $('.aviso_conta_finan').show();
                    }
            }
        });


    });
});



$(".form_inc").on("submit","form",function(e){
     e.preventDefault();



     var dados = $(this).serialize();
     $.post("{% url 'create_receita' %}",dados,function(result){
        $(".form_inc").html(result);
        if(close_modal==true){
           $('.form_inc').hide("drop");
           $('.table_lancfinanceiro').show("puff");
           $('.btn_lancamentos').show();
           window.location.reload();
        }
        else{
            $(".form_inc").show();
            {% include 'js_floating_labels.html' %}
            {% include 'js_tabs.html' %}
            $('.chosen-select').chosen({ width: '100%' });





               $(".form_inc .cancel_form").on("click",function(e){
                    $('.form_inc').hide("drop");
                    $('.table_lancfinanceiro').hide("drop");
                    $('.btn_lancamentos').show();
               });


        }
     });
});

lancfinanceiros/templates/js_info_lancamentos.html
$(".table_lancfinanceiro").on("click",".info_lancto",function(e){
   e.preventDefault();
   $("#modal-infolancto .block-content").load($(this).attr('href'), function(){
       $('#modal-infolancto').modal("show");
       $('.titulo_modal').text("Informações Lançamento");
       {% include 'js_tabs.html' %}
   });

});