accounts/urls.py
from django.conf.urls import url,include
from django.contrib.auth.views import  login,logout
from accounts import views





urlpatterns = [
    url(r'^$',views.register, name='register'),
    url(r'^registro/sucesso/$' ,views.success_register, name='success_register'),
    url(r'^ativar/(?P<token>\w+)/$',views.user_active, name='user_active'),
    url(r'^recuperar/$',views.recover_account, name='recover_account'),
    url(r'^recuperar/(?P<id>\d+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.create_new_password, name='create_new_password'),
    url(r'^inclui_usuario',views.register_viewer,name='register_viewer'),
    url(r'^altera_usuario/(?P<pk>\d+)',views.edit_viewer,name='edit_viewer'),
    url(r'^reset_password/(?P<pk>\d+)',views.reset_password,name='reset_password')


]

nilusweb/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import login
from core import views
from django.contrib.auth.views import logout
from django.conf.urls.static import  static
from django.conf import settings

urlpatterns = [
    url(r'^$',login,{'template_name' : 'signin.html'}, name='signin'),
    url(r'^conta/', include('accounts.urls')),
    url(r'^principal/', include('principal.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^sair/$', logout, {'next_page': 'signin'}, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recebiveis/urls.py
from django.conf.urls import url, include
from nilusfin import views
from recebiveis import views

urlpatterns = [
    # Listagens dos cadastros
     url(r'^$', views.titrec_list, name='titrec_list'),


    # Titulos a Receber
    url(r'^insere_titulo_receber$',views.create_titrec,name='create_titrec'),
    url(r'^insere_titulo_receber/(?P<pk>\d+)$', views.edit_titrec, name='edit_titrec'),
    url(r'^recebiveis/(?P<pk>\d+)/apagar/$', views.delete_titrec, name='delete_titrec'),

]

recebiveis/models.py
from django.db import models

# Create your models here.





class Recebiveis(models.Model):
    # informação do dono da conta (usuario Master)
    master_user = models.ForeignKey('accounts.User',models.CASCADE,verbose_name='Usuario Master')

    # dados principais (empresa e numero do lançamento)
    num_rec = models.IntegerField('Nº Registro')
    company = models.ForeignKey('niluscad.Company',models.CASCADE,verbose_name='Empresa')
    propriety = models.ForeignKey('niluscad.Propriety',models.CASCADE, verbose_name='Propriedade')

    #dados do titulo
    client = models.ForeignKey('niluscad.CadGeral',models.CASCADE,verbose_name='Cliente')
    dt_lancamento = models.DateTimeField('Data Lançamento',auto_now_add=True)
    dt_vencimento = models.DateField('Data Vencimento')
    plr_financeiro = models.ForeignKey('niluscad.Planofinan',models.PROTECT,verbose_name='Plano Financeiro')
    conta_receb = models.ForeignKey('nilusfin.Contafinanceira',models.PROTECT,verbose_name='Conta Recebimento')
    c_custo = models.ForeignKey('niluscad.Ccusto',models.PROTECT,verbose_name='Centro de Custo')
    vlr_lancamento = models.DecimalField('Valor do Lançamento',max_digits=13,decimal_places=2,blank=True,null=True)
    valor_text = models.CharField(verbose_name='Valor',  max_length=20)

    #Dados Cotação/Indice
    indice = models.ForeignKey('nilusfin.Indice',models.PROTECT,null=True,blank=True)
    cotacao = models.ForeignKey('nilusfin.Cotacao',models.PROTECT,null=True,blank=True)



    #Dados Baixa e Situação
    statusTit_Choices = (
        ('A', 'Ativo'),
        ('B', 'Baixado'),
        ('C', 'Cancelado'),
    )

    situacao = models.CharField('Situação',max_length=1,choices=statusTit_Choices)
    data_baixa = models.DateTimeField('Data de Recebimento',null=True,blank=True)
    lancamento_pai = models.ForeignKey('self',models.SET_NULL,blank=True,null=True,verbose_name='Lançamento Pai')

    # Dados Baixa e Situação
    tipoLancto_Choices = (
        ('R', 'Recebimento'),
        ('P', 'Pagamento'),
    )

    tipo_lancamento = models.CharField('Tipo', max_length=1, choices=tipoLancto_Choices)


    def verifica_parcela(self):
        if self.lancamento_pai:
            return True
        return Recebiveis.objects.filter(lancamento_pai=self).exists()


    def altera_parcelas(self):
        if self.lancamento_pai:
            parcelas = Recebiveis.objects.filter(
                models.Q(lancamento_pai=self.lancamento_pai) | models.Q(pk=self.lancamento_pai.pk)
            )
            parcelas.update(
                plr_financeiro=self.plr_financeiro,c_custo=self.c_custo,valor_text=self.valor_text,
                vlr_lancamento = self.vlr_lancamento,indice=self.indice,cotacao=self.cotacao
            )
        else:
            parcelas = Recebiveis.objects.filter(lancamento_pai = self)
            parcelas.update(
                plr_financeiro=self.plr_financeiro, c_custo=self.c_custo,valor_text=self.valor_text,
                vlr_lancamento=self.vlr_lancamento, indice=self.indice, cotacao=self.cotacao
            )

    class Meta:
        verbose_name = 'Lançamento'
        verbose_name_plural = 'Lançamentos'
        unique_together = [
            ('master_user', 'num_rec')
        ]

    def __str__(self):
        'Lançamento #{}'.format(self.num_lanc)

recebiveis/forms.py
from accounts.models import User
from niluscad.models import Company,Propriety,Cadgeral,Ccusto,PlanoFinan,Cadgeral
from django import forms
from nilusfin.models import Contafinanceira,Cotacao,Indice
from .models import Recebiveis



class FormCreateTitRec(forms.ModelForm):
    parcela = forms.BooleanField(label='Parcelar',required=False)
    qtd = forms.IntegerField(label='Quantidade',required=False)
    cc_custo_extra = forms.CharField



    tipo_rept = forms.ChoiceField(label='Período',choices=(
        ('M','Mês'),('S', 'Semana'),('D','Dia')))


    def clean_qtd(self):
        parcela = self.cleaned_data.get('parcela',False)
        qtd = self.cleaned_data.get('qtd',None)
        if parcela and not qtd:
            raise forms.ValidationError('Preencher a quantidade de parcelas do titulo')
        return qtd

    def __init__(self,user,*args,**kwargs):
        super(FormCreateTitRec,self).__init__(*args,**kwargs)
        if user.is_masteruser is True:
            self.fields['company'].queryset = Company.objects.filter(master_user=user)
            self.fields['propriety'].queryset = Propriety.objects.filter(master_user=user)
            self.fields['client'].queryset = Cadgeral.objects.filter(master_user=user,cliente=True)
            self.fields['plr_financeiro'].queryset = PlanoFinan.objects.filter(master_user=user,sinal='R')
            self.fields['c_custo'].queryset = Ccusto.objects.filter(master_user=user)
            self.fields['indice'].queryset = Indice.objects.filter(master_user=user)
            self.fields['cotacao'].queryset = Cotacao.objects.filter(master_user=user)
            self.fields['conta_receb'].queryset = Contafinanceira.objects.filter(master_user=user,
                                                                                 conta_recebimento=True)
        else:
            self.fields['company'].queryset = Company.objects.filter(master_user=user.user_master)
            self.fields['propriety'].queryset = Propriety.objects.filter(master_user=user.user_master)
            self.fields['client'].queryset = Cadgeral.objects.filter(master_user=user.user_master, cliente=True)
            self.fields['plr_financeiro'].queryset = PlanoFinan.objects.filter(master_user=user.user_master, sinal='R')
            self.fields['c_custo'].queryset = Ccusto.objects.filter(master_user=user.user_master)
            self.fields['indice'].queryset = Indice.objects.filter(master_user=user.user_master)
            self.fields['cotacao'].queryset = Cotacao.objects.filter(master_user=user.user_master)
            self.fields['conta_receb'].queryset = Contafinanceira.objects.filter(master_user=user.user_master,
                                                                                 conta_recebimento=True)

    class Meta:
        model = Recebiveis
        fields = ['company','propriety','client','dt_vencimento','plr_financeiro','c_custo','conta_receb','valor_text',
                  'indice','cotacao']



class FormEditTitRec(forms.ModelForm):

    def __init__(self,user,*args,**kwargs):
        super(FormEditTitRec,self).__init__(*args,**kwargs)
        if user.is_masteruser is True:
            self.fields['plr_financeiro'].queryset = PlanoFinan.objects.filter(master_user=user, sinal='R')
            self.fields['c_custo'].queryset = Ccusto.objects.filter(master_user=user)
            self.fields['indice'].queryset = Indice.objects.filter(master_user=user)
            self.fields['cotacao'].queryset = Cotacao.objects.filter(master_user=user)
            self.fields['conta_receb'].queryset = Contafinanceira.objects.filter(master_user=user,
                                                                                 conta_recebimento=True)
        else:
            self.fields['plr_financeiro'].queryset = PlanoFinan.objects.filter(master_user=user.user_master, sinal='R')
            self.fields['c_custo'].queryset = Ccusto.objects.filter(master_user=user.user_master)
            self.fields['indice'].queryset = Indice.objects.filter(master_user=user.user_master)
            self.fields['cotacao'].queryset = Cotacao.objects.filter(master_user=user.user_master)
            self.fields['conta_receb'].queryset = Contafinanceira.objects.filter(master_user=user.user_master,
                                                                                 conta_recebimento=True)

    class Meta:
        model = Recebiveis
        fields = ['dt_vencimento','plr_financeiro','c_custo','conta_receb','valor_text',
                  'indice','cotacao']




class FiltroRecebimentosForm(forms.Form):

    data_venc_ini = forms.DateField(label='Vencimento de:', required=False)
    data_venc_fim = forms.DateField(label='Vencimento até:', required=False)

    data_lanc_ini = forms.DateField(label='Lançamento de:', required=False)
    data_lanc_fim = forms.DateField(label='Lançamento até:', required=False)

    empresa = forms.ModelChoiceField(label='Empresa',required=False,empty_label='Todos', queryset=Company.objects.none())
    propriedade = forms.ModelChoiceField(label='Propriedade', required=False, queryset=Propriety.objects.none())
    cliente = forms.ModelChoiceField(label='Cliente', required=False, queryset=Cadgeral.objects.none())
    plano_finan = forms.ModelChoiceField(label='Plano Financeiro', required=False, queryset=PlanoFinan.objects.none())
    c_custo = forms.ModelChoiceField(label='Centro de Custo', required=False, queryset=Ccusto.objects.none())



    def __init__(self,empresa,propriedade,cliente,plano_finan,c_custo,  *args,**kwargs):
        super(FiltroRecebimentosForm,self).__init__(*args,**kwargs)
        self.fields['empresa'].queryset = empresa
        self.fields['propriedade'].queryset = propriedade
        self.fields['cliente'].queryset = cliente
        self.fields['plano_finan'].queryset = plano_finan
        self.fields['c_custo'].queryset = c_custo

recebiveis/templates/_create_titrec.html
{% load static widget_tweaks %}
{% if success %}
   <script>
  	 close_modal=true;
   </script>
{% else %}
<div class="card-header">
    <h4 class="m-b-0 text-white">Inclusão Receita<button type="button" class="close cancel_create">×</button></h4>
</div>
<div class="card-body">
 <form  class="form-horizontal titrec" method="post">
{% csrf_token %}
{% for error in form.non_field_errors %}
    <div class="alert-danger alert">
        {{ error }}
    </div>
{% endfor %}
    <div class="form-body">
        <h5 class="box-title">Empresa/Propriedade</h5>
        <hr class="m-t-0 m-b-10">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label col-md-2">{{ form.company.label_tag  }}</label>
                    <div class="col-md-9">
                        {% render_field form.company class="chosen-select" style="width: 100%; height:36px;" %}
                        {% for error in form.company.errors %}
                        <small class="text-danger form-control-feedback"> {{ error }} </small>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <!--/span-->
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label col-md-3">{{ form.propriety.label_tag }}</label>
                    <div class="col-md-9">
                        {% render_field form.propriety class="chosen-select" style="width: 100%; height:36px;" %}
                        {% for error in form.propriety.errors %}
                        <small class="text-danger form-control-feedback"> {{ error }} </small>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <!--/span-->
        </div>
          <hr class="m-t-5 m-b-10">
        <h5 class="box-title">Dados do Lançamento</h5>
        <hr class="m-t-0 m-b-10">
        <!--/row-->
        <div class="row">
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label  col-md-2">{{ form.client.label_tag }}</label>
                    <div class="col-md-9">
                        {% render_field form.client class="chosen-select" style="width: 100%; height:36px;"  %}
                        {% for error in form.client.errors %}
                        <small class="text-danger form-control-feedback"> {{ error }} </small>
                        {% endfor %}


                    </div>
                             <button type="button" title="Novo Cliente" class="btn btn-warning btn-circle new_cadgeral"><i class="fa fa-plus"></i> </button>
                </div>
            </div>
            <!--/span-->
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label text-right col-md-4">Vencimento:</label>
                    <div class="col-md-8">
                        {% render_field form.dt_vencimento  placeholder='dd/mm/aaaa' class='form-control datepicker' %}
                        <!--<input type="date" name="dt_vencimento"  class="form-control" placeholder="dd/mm/aaaa" required="" id="id_dt_vencimento">-->
                        {% for error in form.dt_vencimento.errors %}
                        <small class="text-danger form-control-feedback"> {{ error }} </small>
                        {% endfor %}
                    </div>

                </div>
            </div>
            <!--/span-->
        </div>

        <!--/row-->

        <div class="row">
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label col-md-4">{{ form.plr_financeiro.label_tag }}</label>
                    <div class="col-md-7">
                         {% render_field form.plr_financeiro class="chosen-select" style="width: 100%; height:36px;" %}
                        {% for error in form.plr_financeiro.errors %}
                        <small class="text-danger form-control-feedback"> {{ error }} </small>
                        {% endfor %}
                    </div>
                    <!--
                    <div class="dropdown">
                    <button type="button" title="Novo Plano Financeiro" class="btn btn-warning btn-circle new_planofin" data-toggle="dropdown"><i class="fa fa-plus"></i> </button>
                        <div class="dropdown-menu dpdown_planofinan" style="padding: 10px;">

                        </div>
                    </div>
                  -->
                 <button type="button" title="Novo Plano Financeiro" class="btn btn-warning btn-circle new_planofin" data-container="body" data-toggle="popover" data-placement="bottom"><i class="fa fa-plus"></i> </button>
                </div>

            </div>


            <!--/span-->
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label col-md-4">{{ form.c_custo.label_tag }}</label>
                    <div class="col-md-7">
                            {% render_field form.c_custo class="chosen-select" style="width: 100%; height:36px;" id="c_custo_id2" %}
                        {% for error in form.c_custo.errors %}
                        <small class="text-danger form-control-feedback"> {{ error }} </small>
                        {% endfor %}
                    </div>
                       <button type="button" class="btn btn-warning btn-circle new_ccusto" title="Novo Centro de Custo" data-container="body" data-toggle="popover2" data-placement="bottom"><i class="fa fa-plus"></i> </button>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label col-md-4">{{ form.conta_receb.label_tag }}</label>
                    <div class="col-md-7">
                            {% render_field form.conta_receb class="chosen-select" style="width: 100%; height:36px;" %}
                        {% for error in form.conta_receb.errors %}
                        <small class="text-danger form-control-feedback"> {{ error }} </small>
                        {% endfor %}
                    </div>
                    <button type="button" class="btn btn-warning btn-circle new_conta" title="Nova Conta de Recebimento" data-container="body" data-toggle="popover3" data-placement="bottom"><i class="fa fa-plus"></i> </button>
                </div>
            </div>
            <!--/span-->
        </div>
              <hr class="m-t-0 m-b-10">
        <h5 class="box-title">Valores</h5>
         <hr class="m-t-0 m-b-10">
        <!--/row-->
        <div class="row">
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label text-right col-md-3">{{ form.valor_text.label_tag }}</label>
                    <div class="col-md-9">
                        {% render_field  form.valor_text class="form-control" data-thousands="." data-decimal="," data-prefix="R$ " %}
                        {% for error in form.valor_text.errors %}
                        <small class="text-danger form-control-feedback"> {{ error }} </small>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group row">
                     <div class="checkbox checkbox-success col-md-3">
                         {% render_field form.parcela type="checkbox" %}
                         <label for="id_parcela">Parcela</label>
                         {% for error in form.parcela.errors %}
                         <small class="form-control-feedback"> {{ error }} </small>
                         {% endfor %}
                     </div>
                    <div class="col-md-3 parcela">
                        <label class="control-label text-right">{{ form.qtd.label_tag }}</label>
                        {% render_field form.qtd class='form-control'  %}
                        {% for error in form.qtd.errors %}
                        <small class="form-control-feedback"> {{ error }} </small>
                         {% endfor %}
                    </div>
                    <div class="col-md-1 parcela"></div>
                    <div class="col-md-4 parcela">
                        <label class="control-label text-right">{{ form.tipo_rept.label_tag }}</label>
                        {% render_field form.tipo_rept class='form-control'  %}
                        {% for error in form.tipo_rept.errors %}
                        <small class="form-control-feedback"> {{ error }} </small>
                         {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label text-right col-md-3">{{  form.cotacao.label_tag }}</label>
                    <div class="col-md-9">
                        {% render_field form.cotacao class="chosen-select" style="width: 100%; height:36px;" %}
                        {% for error in form.cotacao.errors %}
                        <small class="form-control-feedback"> {{ error }} </small>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="control-label text-right col-md-3">{{ form.indice.label_tag }}</label>
                    <div class="col-md-9">
                        {% render_field form.indice class="select2 form-control custom-select" style="width: 100%; height:36px;" %}
                        {% for error in form.indice.errors %}
                        <small class="form-control-feedback"> {{ error }} </small>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <!--/span-->
    </div>
    <hr>
    <div class="form-actions">
        <div class="row">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn btn-success">Salvar</button>
                        <a type="button"  id="cancel_create" href="#" class="btn btn-inverse cancel_create">Cancelar</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6"> </div>
        </div>
    </div>
</form>
</div>

{% endif %}

recebiveis/templates/_select_propriety.html
{% load l10n %}
{% for prop in propriety %}
    <option{% if user.propriety_p == prop  %} selected{% endif %} value="{{ prop.pk|unlocalize }}">{{ prop.razao }}</option>
{% endfor %}

recebiveis/templates/create_titrec.html
{% extends "menu.html" %}
{% load static widget_tweaks humanize %}



<!-- Bread crumb and right sidebar toggle -->
{% block title_page %} Titulos a Receber {% endblock %}

{% block page_body %}



<div class="card card-outline-success">
    <div class="card-header">
        <h4 class="m-b-0 text-white">Inclusão de titulo </h4>
    </div>
    <div class="card-body">
       {% include '_create_titrec.html' %}
    </div>
</div>


<div id="modal-cadgeral" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="title-modal"></h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>






{% endblock %}


{% block javascript %}

$('.chosen-select').chosen({ width: '100%' });
$("#id_valor_text").maskMoney();
$(".parcela").hide();


$(".titrec").on("change", "#id_parcela", function(e){
			if ($(this).is(":checked")){
				$(".parcela").show();
			}
			else {
				$(".parcela").hide();

			}
		});

 function load_propriety(){
        var company_id = $('#id_company').val();
        if(company_id != ''){
            var url = '{% url 'company_propriety' %}';
            url = url+'?company_id='+company_id;
            $("#id_propriety").load(url,function(){
                $("#id_propriety").trigger("chosen:updated");
             });
        }
        else{
          $("#id_propriety").html('');
        }
    }



              $("#id_company").on("change",function(e){

                  load_propriety();
              });

              load_propriety();


$(".new_cadgeral").on("click",function(e){
    e.preventDefault();

    $("#modal-cadgeral .modal-body").load("{% url 'create_cadgeral' %}", function(){
          $('#title-modal').text("Inclusão de Cadastro");
          $('#modal-cadgeral').modal("show");
          $(".btn_busca").hide();
          $(".campo_obrigatorio").hide();
          $(".principal").hide();
          $(".endereco").hide();
          $(".contato").hide();
          $(".pos_submit_cnpj").hide();
          $(".pos_submit_razao").hide();
          $(".pos_submit_endereco").hide();
          $("#id_cnpj_cpf").focus();


          $("#id_cnpj_cpf").keyup(function(e){
            if($(this).val().length > 12){
                $(".btn_busca").show();
            }
          });

                  function limpa_formulario_cadastro(){
                           $("#id_cnpj_cpf").val("");
			               $("#id_razao").val("");
				           $("#id_fantasia").val("");
				           $("#id_cep").val("");
				           $("#id_endereco").val("");
				           $("#id_numero").val("");
				           $("#id_complemento").val("");
				           $("#id_bairro").val("");
				           $("#id_uf").val("");
			      }

                  $("#btn_busca_cnpj").on("click",function(e){
				        var cnpj = $("#id_cnpj_cpf").val().replace(/\D/g, '');

				    if (cnpj != "") {
                        //Preenche os campos com "..." enquanto consulta webservice.
                            $("#id_razao").val("...");
                            $("#id_fantasia").val("...");
                            $("#id_cep").val("...");
                            $("#id_endereco").val("...");
                            $("#id_numero").val("...");
                            $("#id_complemento").val("...");
                            $("#id_bairro").val("...");
                            $("#id_uf").val("...");

                            //Consulta o webservice receitaws.com.br/
                            $.getJSON("//www.receitaws.com.br/v1/cnpj/"+cnpj, function(dados) {
                            var checkcnpj = dados.cnpj

                            if(checkcnpj != undefined){
                                       //Atualiza os campos com os valores da consulta.
                                    $("#id_razao").val(dados.nome);
                                    $("#id_fantasia").val(dados.fansasia);
                                    $("#id_cep").val(dados.cep);
                                    $("#id_endereco").val(dados.logradouro);
                                    $("#id_numero").val(dados.numero);
                                    $("#id_complemento").val(dados.complemento);
                                    $("#id_bairro").val(dados.bairro);
                                    $("#id_uf").val(dados.uf);
                            }
                            else {
                                limpa_formulario_cadastro();
                                alert("cnpj inválido");
                            }


                       });
                      } //end if.
                      else {
                             //CNPJ sem valor, limpa formulário.
                             limpa_formulario_cadastro();
                      }
			      });


                  function limpa_formulário_cep() {
                    // Limpa valores do formulário de cep.
                    $("#id_endereco").val("");
                    $("#id_bairro").val("");
                    $("#id_cidade").val("");
                    $("#id_uf").val("");
                  }

                  $("#id_cep").blur(function() {

                    //Nova variável "cep" somente com dígitos.
                    var cep = $(this).val().replace(/\D/g, '');

                    //Verifica se campo cep possui valor informado.
                    if (cep != "") {

                        //Expressão regular para validar o CEP.
                        var validacep = /^[0-9]{8}$/;

                        //Valida o formato do CEP.
                        if(validacep.test(cep)) {

                            //Preenche os campos com "..." enquanto consulta webservice.
                            $("#id_endereco").val("...");
                            $("#id_bairro").val("...");
                            $("#id_cidade").val("...");
                            $("#id_uf").val("...");

                            //Consulta o webservice viacep.com.br/
                            $.getJSON("//viacep.com.br/ws/"+ cep +"/json/?callback=?", function(dados) {

                                if (!("erro" in dados)) {
                                    //Atualiza os campos com os valores da consulta.
                                    $("#id_endereco").val(dados.logradouro);
                                    $("#id_bairro").val(dados.bairro);
                                    $("#id_cidade").val(dados.localidade);
                                    $("#id_uf").val(dados.uf);
                                } //end if.
                                else {
                                    //CEP pesquisado não foi encontrado.
                                    limpa_formulário_cep();
                                    alert("CEP não encontrado.");
                                }
                            });
                        } //end if.
                        else {
                            //cep é inválido.
                            limpa_formulário_cep();
                            alert("Formato de CEP inválido.");
                        }
                    } //end if.
                    else {
                        //cep sem valor, limpa formulário.
                        limpa_formulário_cep();
                    }
                  });


                $(".submit").on("click",function(e){
                    if($("#id_cnpj_cpf").val().length < 0){
                        $(".pos_submit_cnpj").hide();
                        $(".campo_obrigatorio").show();
                        $(".principal").show();
                        e.preventDefault();
                    }

                    if($("#id_razao").val().length == 0){
                        $(".pos_submit_razao").hide();
                        $(".campo_obrigatorio").show();
                        $(".principal").show();
                        e.preventDefault();

                    }

                    if($("#id_endereco").val().length == 0){
                        $(".pos_submit_endereco").show();
                        $(".campo_obrigatorio").show();
                        $(".endereco").show();
                        e.preventDefault();
                    }
			    });

                $(".cancel").on("click",function(e){
                         $("#form_create").hide();
			    });


               });


});


$("#modal-cadgeral .modal-body").on("submit","form",function(e){
	 	 e.preventDefault();
	 	 var dados = $(this).serialize();
	 	 $.post("{% url 'create_cadgeral' %}",dados,function(result){
	 	    $("#modal-cadgeral .modal-body").html(result);
	 	    if(close_modal==true){
	 	       $('#modal-cadgeral').modal("hide");
               $('#id_client').append("<option value='" + id_cliente + "'>"+ nome_cliente + "</option>");
			   $('#id_client').val(id_cliente);
			   $('#id_client').trigger('chosen:updated');



	 	    }
	 	    else{
	 	       $('#modal-cadgeral').modal("show");
	 	    }
	 	 });
	 });








{% endblock %}