accounts/urls.py
from django.conf.urls import url,include
from django.contrib.auth.views import  login,logout
from accounts import views





urlpatterns = [
    url(r'^$',views.register, name='register'),
    url(r'^registro/sucesso/$' ,views.success_register, name='success_register'),
    url(r'^ativar/(?P<token>\w+)/$',views.user_active, name='user_active'),
    url(r'^recuperar/$',views.recover_account, name='recover_account'),
    url(r'^recuperar/(?P<id>\d+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.create_new_password, name='create_new_password'),
    url(r'^inclui_usuario',views.register_viewer,name='register_viewer'),
    url(r'^altera_usuario/(?P<pk>\d+)',views.edit_viewer,name='edit_viewer'),
    url(r'^reset_password/(?P<pk>\d+)',views.reset_password,name='reset_password')


]

nilusfin/urls.py
from django.conf.urls import url,include
from nilusfin import views


urlpatterns = [
    # Listagens dos cadastros
    url(r'^conta/$',views.conta_list,name='conta_list'),
    url(r'^indice/$',views.indice_list,name='indice_list'),
    url(r'^cotacao/(?P<pk>\d+)$',views.cotacao_list,name='cotacao_list'),

    # Conta
    url(r'^insere_conta/$', views.create_conta, name='create_conta'),
    url(r'^insere_conta/(?P<pk>\d+)$', views.edit_conta, name='edit_conta'),
    url(r'^conta/(?P<pk>\d+)/apagar/$', views.delete_conta, name='delete_conta'),
    url(r'^conta/ajuste',views.ajc_saldoconta,name='ajc_saldoconta'),

    # Indices
    url(r'^insere_indice/$', views.create_indice, name='create_indice'),
    url(r'^insere_indice/(?P<pk>\d+)/$', views.edit_indice, name='edit_indice'),
    url(r'^indice/(?P<pk>\d+)/apagar/$', views.delete_indice, name='delete_indice'),
    url(r'^insere_indice_lancto/$', views.create_indice_lancto, name='create_indice_lancto'),

    # Cotações
    url(r'^insere_cotacao/$', views.create_cotacao_create_indice, name='create_cotacao_create_indice'),
    url(r'^insere_cotacao/grid/$', views.create_cotacao_grid_indice, name='create_cotacao_grid_indice'),
    url(r'^insere_cotacao_edit/$', views.create_cotacao_edit_indice, name='create_cotacao_edit_indice'),
    url(r'^delete_cotacao/(?P<pk>\d+)/$', views.delete_cotacao, name='delete_cotacao'),

    # url(r'^cotacao/(?P<pk>\d+)/apagar/$', views.delete_cotacao, name='delete_cotacao'),


    # # Lançamentos
    # url(r'lancamentos',views.lancto_list,name='lancto_list'),
    # url(r'însere_lanc_r',views.create_titrec,name='create_titrec'),
    # url(r'edit_lancto/(?<pk>\d+)$',views.edit_lancto,name='edit_lancto'),

    # Consultas e Extratos
    url(r'^extrato_contas',views.extrato_contas,name='extrato_contas'),


    # DRE
    url(r'^consulta_dre',views.dre_list,name='dre_list'),


    # FLUXO DE CAIXA
    url(r'^fluxo_caixa',views.fluxo_caixa,name='fluxo_caixa'),
    # url(r'^fluxo_caixa/consulta',views.fluxo_caixa_consulta,name='fluxo_caixa_consulta')
]

nilusweb/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import login
from core import views
from django.contrib.auth.views import logout
from django.conf.urls.static import  static
from django.conf import settings

urlpatterns = [
    url(r'^$',login,{'template_name' : 'signin.html'}, name='signin'),
    url(r'^conta/', include('accounts.urls')),
    url(r'^principal/', include('principal.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^sair/$', logout, {'next_page': 'signin'}, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nilusfin/models.py
from django.db import models

# Create your models here.

class Contafinanceira(models.Model):

    # informação do dono da conta (usuario Master)
    master_user = models.ForeignKey('accounts.User',models.CASCADE,verbose_name='Usuario Master')
    num_conta = models.IntegerField('Código')

    # dados principais
    conta_bancaria = models.BooleanField('Conta Bancária?',default=False)
    agencia = models.CharField('Agencia',null=True,blank=True,max_length=5)
    conta = models.CharField('Conta',null=True,blank=True,max_length=12)
    descricao = models.CharField('Nome Conta',max_length=60)

    #dados de limite
    usa_limite = models.BooleanField('Utiliza Limite',default=False)
    vlr_limite = models.DecimalField('Valor Limite',decimal_places=2,max_digits=50,default=0)
    vlr_limite_text = models.CharField('Valor Limite',null=True,blank=True,max_length=50)

    #dados de movimentação
    conta_pagamento = models.BooleanField('Conta de Pagamento?',default=False)
    conta_recebimento = models.BooleanField('Conta de Recebimento?', default=False)



    class Meta:
        verbose_name = 'Contas'
        verbose_name_plural = 'Contas'
        unique_together = [
            ('master_user', 'num_conta')
        ]


    def __str__(self):
        return self.descricao



class Indice(models.Model):

    # informação do dono da conta (usuario Master)
    master_user = models.ForeignKey('accounts.User',models.CASCADE,verbose_name='Uusario Master')
    num_indice = models.IntegerField('Código')

    # dados principais
    descricao = models.CharField('Nome Indice',max_length=20)
    simbolo = models.CharField('Simbolo', max_length=5)

    indice_padrao = models.BooleanField('Indice Padrao',default=False)


    class Meta:
        verbose_name = 'Indice'
        verbose_name_plural = 'Indices'
        unique_together = [
          ('master_user', 'num_indice')
        ]


    def __str__(self):
        return self.descricao



class Cotacao(models.Model):
    # informação do dono da conta (usuario Master)
    # master_user = models.ForeignKey('accounts.User', models.CASCADE, verbose_name='Uusario Master')
    indice = models.ForeignKey('nilusfin.Indice',models.PROTECT,verbose_name='Indice',null=True,blank=True)

    data_indice = models.DateField('Data',null=True,blank=True)
    valor_cotacao = models.DecimalField('Valor',null=True,blank=True,decimal_places=4,max_digits=13)
    valor_cotacao_text = models.CharField(verbose_name='Valor', max_length=20)
    user_cad = models.ForeignKey('accounts.User',models.SET_NULL, verbose_name='Usuario Criação',null=True,blank=True)

    cotacao_padrao = models.BooleanField('Cotação Padrão',default=False)

    class Meta:
        verbose_name = 'Cotacao'
        verbose_name_plural = 'Cotações'
        unique_together = [
            ('indice', 'data_indice')
        ]



    def __str__(self):
        return str(self.valor_cotacao_text)

nilusfin/forms.py
from accounts.models import User
from django import forms
from .models import Cotacao,Indice,Contafinanceira
from niluscad.models import Company
from lancfinanceiros.models import Movtos_lancamentos


class FormCreateCotacao(forms.ModelForm):

    def __init__(self,user,*args,**kwargs):
        super(FormCreateCotacao,self).__init__(*args,**kwargs)
        if user.is_masteruser:
            self.fields['indice'].queryset=Indice.objects.filter(master_user=user)
            self.fields['indice'].empty_label = 'Selecione um indice'
        else:
            self.fields['indice'].queryset = Indice.objects.filter(
                master_user=user.user_master
            )
            self.fields['indice'].empty_label = 'Selecione um indice'


    class Meta:
            model = Cotacao
            fields = ['indice','data_indice','valor_cotacao_text']




class FormAjusteSaldo(forms.ModelForm):
    vlr_novosaldo = forms.CharField(max_length=20)
    saldo_negativo = forms.BooleanField(label='Saldo Negativo', required=False)


    def __init__(self, user, *args, **kwargs):
        super(FormAjusteSaldo, self).__init__(*args, **kwargs)
        if user.is_masteruser is True:
            self.fields['conta_financeira'].queryset = Contafinanceira.objects.filter(master_user=user)
            self.fields['company'].queryset = Company.objects.filter(master_user=user)

        else:
            self.fields['conta_financeira'].queryset = Contafinanceira.objects.filter(master_user=user.user_master)
            self.fields['company'].queryset = Company.objects.filter(master_user=user.user_master)



        self.fields['conta_financeira'].empty_label = 'Selecione uma conta'
        self.fields['company'].empty_label = 'Selecione uma empresa'

    class Meta:
        model = Movtos_lancamentos
        fields = ['conta_financeira','dt_movimento','company']



class FiltroLancamentosExtrato(forms.Form):
    data_lanc_ini = forms.DateField(label='Lançamento de:', required=True)
    data_lanc_fim = forms.DateField(label='Lançamento até:', required=True)
    empresa = forms.ModelChoiceField(label='Empresa',empty_label='Todas',required=False,queryset=Company.objects.none())
    conta_finan = forms.ModelChoiceField(label='Conta Financeira',empty_label='Todas',required=False,queryset=Contafinanceira.objects.none())

    def __init__(self, conta_finan,empresa, *args, **kwargs):
        super(FiltroLancamentosExtrato, self).__init__(*args, **kwargs)
        self.fields['conta_finan'].queryset = conta_finan
        self.fields['empresa'].queryset=empresa



class FiltroDre(forms.Form):
    data_lanc_ini = forms.DateField(label='Lançamento de:', required=True)
    data_lanc_fim = forms.DateField(label='Lançamento até:', required=True)
    empresa = forms.ModelChoiceField(label='Empresa',empty_label='Todas',required=False,queryset=Company.objects.none())


    f_lancamento = parcela = forms.BooleanField(label='Data Lançamento', required=False)
    f_vencimento = forms.BooleanField(label='Data Vencimento', required=False)
    f_baixa = forms.BooleanField(label='Data Baixa', required=False)

    def __init__(self,empresa, *args, **kwargs):
        super(FiltroDre, self).__init__(*args, **kwargs)
        self.fields['empresa'].queryset= empresa


class FormFluxoCaixa(forms.Form):
    data_venc_ini = forms.DateField(label='Vencimento de:', required=True)
    data_venc_fim = forms.DateField(label='Vencimento até:', required=True)
    empresa = forms.ModelChoiceField(label='Empresa', empty_label='Todas', required=False,
                                     queryset=Company.objects.none())
    contas_financeiras = forms.ModelMultipleChoiceField(queryset=Contafinanceira.objects.none())
    considera_atraso = forms.BooleanField(label='Considera Atrasados',required=False)

    def __init__(self,empresa,contas,*args, **kwargs):
        super(FormFluxoCaixa, self).__init__(*args, **kwargs)
        self.fields['contas_financeiras'].queryset = contas
        self.fields['empresa'].queryset = empresa

nilusfin/templates/_table_indice.html
    <table id="tabela_indice" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th style="width:20px;">Cód</th>
                        <th>Indice</th>
                        <th style="width:30px;">Símbolo</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                {% for in in indice %}
                 {% if in.indice_padrao == False %}
                    <tr>

                        <td>{{ in.num_indice }}</td>
                        <td>{{ in.descricao }}</td>
                        <td>{{ in.simbolo }}</td>
                        <td>
                            <div class="pull-right">
                             <button type="button" class="btn btn-sm btn-outline-secondary edit_indice"  href="{% url 'edit_indice' in.pk  %}" data-toggle="tooltip" data-placement="bottom" title="Editar">
                                <i class="fa fa-pencil"></i>
                             </button>

                             <button type="button" class="btn btn-sm btn-outline-danger delete_indice"  href="{% url 'delete_indice' in.pk  %}" data-toggle="tooltip" data-placement="bottom" title="Excluir">
                                <i class="fa fa-trash-o"></i>
                             </button>

                             <button type="button" class="btn btn-sm btn-outline-info lista_cotacoes"  href="{% url 'cotacao_list' in.pk  %}" data-toggle="tooltip" data-placement="bottom" title="Visualizar Cotações">
                                 <i class="si si-layers"></i>
                             </button>
                            </div>
                        </td>
                    </tr>
                 {% endif %}
                {% endfor %}
                </tbody>
            </table>

nilusfin/templates/conta_list_antigo_layout.html
{% extends "menu.html" %}
{% load static widget_tweaks humanize %}



<!-- Bread crumb and right sidebar toggle -->
{% block title_page %} Contas Bancárias/Caixa {% endblock %}

{% block page_body %}

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Contas</h4>
        <h6 class="card-subtitle">Cadastro das contas (Bancárias e Contas de Caixa)
            <div class="col-lg-2 col-md-4 pull-right new_add">
                     <a class="btn btn-success btn new_add_btn" title="Cadastrar " href="{% url 'create_conta' %}"><i class="fa fa-plus"></i><small> Cadastrar</small></a>
            </div>
        </h6>

        <div class="table-responsive table_data">
          {% include '_table_conta.html' %}
        </div>
    </div>
</div>


<div id="modal-create" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Criar Conta</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>



<div id="modal-update" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Atualizar dados de Conta</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>




{% endblock %}


{% block javascript %}




function loading_contas(){
      $('.table_data').load('{{ request.path }}');
	}


 $('#myTable').DataTable({
     "language": {
         "lengthMenu": "Mostrando _MENU_ registros por página",
         "search" : "Procurar: ",
         "info" : "Exibindo de _START_ a _END_ de _TOTAL_ registros",
         "infoEmpty": "Nenhum registro encontrado",
         "infoFiltered": "(filtrado entre _MAX_ registros)",
         "paginate" : {
           "first":      "Primeiro",
           "last":       "Último",
           "next":       "Próximo",
           "previous":   "Anterior"
         },
     }
});



 $(".modal").on("change", "#id_usa_limite", function(e){
			if ($(this).is(":checked")){
				$(".vlr_limite").show();
			}
			else {
				$(".vlr_limite").hide();
			}
		});




<!-- Create Viewer -->
$(".new_add").on("click",".new_add_btn", function(e){
				e.preventDefault();
				$("#modal-create .modal-body").load("{% url 'create_conta' %}", function(){
				  $('#modal-create').modal("show");
                  $(".vlr_limite").hide();
                });

});

$("#modal-create .modal-body").on("submit","form",function(e){
	 	 e.preventDefault();
	 	 var dados = $(this).serialize();
	 	 $.post("{% url 'create_conta' %}",dados,function(result){
	 	    $("#modal-create .modal-body").html(result);
	 	    if(close_modal==true){
	 	       $('#modal-create').modal("hide");
               loading_contas();
               window.location.reload()
	 	    }
	 	    else{
	 	       $('#modal-create').modal("show");
	 	    }
	 	 });
	 });







<!-- Update Viewer -->
$(".table_data").on("click", ".edit_registro", function(e){
        e.preventDefault();
  		$("#modal-update .modal-body").load($(this).attr('href'), function(){
              $('#modal-update').modal("show");
                    if($("#id_usa_limite").is(":checked")){
                        $(".vlr_limite").show();
                    }
                    else{
                         $(".vlr_limite").hide();
                    }


			    });
	});

$("#modal-update .modal-body").on("submit","form",function(e){
	 	 e.preventDefault();

	 	 var dados = $(this).serialize();
	 	 $.post($(this).attr('action'),dados,function(result){
	 	    $("#modal-update .modal-body").html(result);
	 	    if(close_modal==true){
	 	       $('#modal-update').modal("hide");
               loading_contas();
               window.location.reload()

	 	    }
	 	    else{
	 	       $('#modal-update').modal("show");
	 	    }
	 	 });
	 });




    $(".delete_registro").on("click", function(e){

        e.preventDefault();
        var linkURL = $(this).attr("href");
        swal({
            title: "Tem certeza?",
            text: "Ao aceitar esta registro será excluido!",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Sim, Excluir!",
            cancelButtonText: "Não, Cancelar!",
            closeOnConfirm: false,
            closeOnCancel: false
        },
        function(isConfirm){
                if (isConfirm) {
                    swal("Excluido!", "Registro excluido com sucesso!", "success");
                    window.location.href = linkURL;
                }
                else {
                    swal("Cancelado", "Exclusão cancelada", "error");
                }
        });
	});














{% endblock %}

nilusfin/templates/extrato_contas.html
{% extends "menu.html" %}
{% load static widget_tweaks humanize %}



<!-- Bread crumb and right sidebar toggle -->
{% block title %} Extrato Movimentações Financeiras {% endblock %}


{% block page_body %}
<div class="block">
    <div class="block-content">
        <div class="block">
            <div class="block-content block-content-full ribbon ribbon-left ribbon-bookmark ribbon-primary">
               <div class="form_busca">
                    <form id="form_busca_movimentos">
                        <div class="filtros_extras">
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="id_data_lanc_ini">Data Lançamento</label>
                                    <div class="input-daterange input-group js-datepicker-enabled" data-date-format="dd/mm/yyyy" data-week-start="1" data-autoclose="true" data-today-highlight="true">
                                        {% render_field form.data_lanc_ini class="form-control js-datepicker"   placeholder="dd/mm/aaaa" data-week-start="1" data-autoclose="true" data-today-highlight="true"%}
                                        <span class="input-group-addon font-w600">  &nbsp; até  &nbsp; </span>
                                        {% render_field form.data_lanc_fim class="form-control js-datepicker"   placeholder="dd/mm/aaaa" data-week-start="1" data-autoclose="true" data-today-highlight="true"%}
                                    </div>
                                </div>
                                <div class="col-md-6 row">
                                    <div class="col-md-7">
                                        <div class="form-material input-group">
                                            <label>{{ form.empresa.label_tag }}</label>
                                            {% render_field form.empresa class="chosen-select" %}
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-material input-group">
                                            <label>{{ form.conta_finan.label_tag }}</label>
                                            {% render_field form.conta_finan class="chosen-select" %}
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-3">

                                        <div class="form-material input-group">
                                            <button type="submit"  class="btn  btn-outline-primary mr-5 mb-5 form_pesquisa form_bus"  id="btn_consultar"  data-toggle="tooltip" data-placement="bottom" title="Consultar Extrato">
                                                <i class="fa fa-search"></i>
                                            </button>
                                            <button type="button" class="btn btn-outline-secondary mr-5 mb-5   btn_opcoes ajc_conta pull-right" data-toggle="tooltip" data-placement="bottom" title="Ajustar Saldo Conta">
                                                    <i class="fa fa-money"></i>
                                            </button>

                                            <button class="btn btn-outline-secondary mr-5 mb-5 btn_lancamentos"
                                                    data-toggle="tooltip" data-placement="bottom" title="Imprimir Extrato"  title=""
                                                    id="btn_impressao"><i class="fa fa-print"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </form>
                </div>
                <br>
                <div class="row">
                    <table class="table table-hover table-vcenter">
                        <thead>
                            <tr>
                                <th style="width: 10px;">Data</th>
                                <th style="width: 700px;">Descrição </th>
                                <th style="width: 20px;">Débito</th>
                                <th style="width: 100px;">Crédito</th>
                                <th class="pull-letf" style="width: 80px;"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th>{{ dt_saldo_ant|date:'d/m/Y' }}</th>
                                <th>Saldo Anterior</th>
                                <td>
                                </td>
                                <td>
                                </td>
                                <th>{% if saldo_anterior < 0  %}<span class="text-danger">{{ saldo_anterior|intcomma }}</span>
                                    {% elif saldo_anterior == 0 %} 0,00
                                    {% else %} <span class="text-success">{{ saldo_anterior|intcomma  }}</span>
                                    {% endif %}
                                </th>
                            </tr>
                            <tr>
                                {% for lanc in lanctos %}
                                    <td>{{ lanc.dt_movimento|date:'d/m/Y' }}</td>
                                <td>
                                    {% if lanc.lancamento %}
                                    <strong>Lancto:</strong> {{ lanc.lancamento.num_lan }}/{{lanc.lancamento.parcela}}
                                    {% endif %}

                                    {% if lanc.lancamento.cadgeral %}
                                     <strong>Cadastro: </strong> {{ lanc.lancamento.cadgeral }}
                                    {% endif %}

                                    {% if lanc.lancamento.descricao %}
                                    <strong>Descrição : </strong>{{ lanc.lancamento.descricao }}</td>
                                    {% endif %}

                                    {% if lanc.tipo_movto == 'A' %}
                                        <strong><span class="text-info">Ajuste de Saldo</span></strong>
                                    {% endif %}
                                    <td>
                                        {% if lanc.sinal == 'D' %}
                                            <span class="text-danger">{{ lanc.vlr_movimento|intcomma }}</span>
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if lanc.sinal == 'R' %}
                                            <span class="text-success">{{ lanc.vlr_movimento|intcomma}}</span>
                                        {% endif %}
                                    </td>
                                    <th></th>
                            </tr>
                            {% endfor %}
                            <tr>
                                <th></th>
                                <th>Soma de Valores no período</th>
                                <th>{% if total_debitos > 0 %}
                                    <span class="text-danger">{{ total_debitos|intcomma }}</span>
                                    {% else %}
                                    0,00
                                    {% endif %}
                                </th>
                                <th>{% if total_creditos > 0 %}
                                    <span class="text-success">{{ total_creditos|intcomma }}</span>
                                    {% else %}
                                    0,00
                                    {% endif %}
                                </th>
                                <th></th>
                            </tr>
                            <tr>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th>

                                </th>
                            </tr>
                            <tr>
                                <th></th>
                                <th>{% if dados_conta.usa_limite == True %} Saldo final conta no período (sem limite)
                                    {% else %} Saldo final conta no período
                                    {% endif %}
                                </th>
                                <th></th>
                                <th></th>
                                <th>
                                     {% if saldo_atual < 0  %}<span class="text-danger">{{ saldo_atual|intcomma }}</span>
                                    {% elif saldo_atual == 0 %} 0,00
                                    {% else %} <span class="text-success">{{ saldo_atual|intcomma  }}</span>
                                    {% endif %}
                                </th>
                            </tr>
                            {% if dados_conta.usa_limite == True %}
                                <tr>
                                    <th></th>
                                    <th>Valor Limite</th>
                                    <th></th>
                                    <th></th>
                                    <th>
                                        {{ dados_conta.vlr_limite_text }}
                                    </th>
                                </tr>
                                <tr>
                                <th></th>
                                <th>Saldo c/ Limite
                                </th>
                                <th></th>
                                <th></th>
                                <th>
                                     {% if saldo_c_limite < 0  %}<span class="text-danger">{{ saldo_c_limite|intcomma }}</span>
                                    {% elif saldo_c_limite == 0 %} 0,00
                                    {% else %} <span class="text-success">{{ saldo_c_limite|intcomma  }}</span>
                                    {% endif %}
                                </th>
                            </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="modal-ajsaldo" tabindex="-1" role="dialog" aria-labelledby="modal-slideright" aria-hidden="true">
    <div class="modal-dialog modal-dialog-slideright" role="document">
        <div class="modal-content">
            <div class="block block-themed block-transparent mb-0">
                <div class="block-header bg-primary-dark">
                    <h3 class="block-title titulo_modal"></h3><h3 class="block-title info_modal"></h3>
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
                            <i class="si si-close"></i>
                        </button>
                    </div>
                </div>
                <div class="block-content">

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-alt-secondary" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>



{% endblock %}

{% block javascript %}
 $('.chosen-select').chosen({ width: '100%' });
{% include 'js_ajuste_saldo.html' %}

var buscou = 'N';


$("#btn_consultar").on("click",function(e){
  buscou = 'S';
});

$("#btn_impressao").on("click",function(e){

    <!--extrato_contas?data_lanc_ini=&data_lanc_fim=&conta_finan=-->


    if(buscou == 'N'){

        var data_lanc_ini = $('#id_data_lanc_ini').val();
        var data_lanc_fim = $('#id_data_lanc_fim').val();


        data_lanc_ini = data_lanc_ini.replace('/','%2F').replace('/','%2F');
        data_lanc_fim = data_lanc_fim.replace('/','%2F').replace('/','%2F');


        var conta_finan =  $('#id_conta_finan').val();
        var empresa = $('#id_empresa').val();

    var url = window.location.href;
    var nova_url = url.replace('/fin/extrato_contas','/rel/extrato_financeiro/');
    var nova_url2 = nova_url + '?data_lanc_ini='+data_lanc_ini+'&data_lanc_fim='+data_lanc_fim+'&empresa='+empresa+'&conta_finan='+conta_finan

    buscou = 'S';
    window.open(nova_url2);

    }else{
        var url = window.location.href;
        var nova_url = url.replace('/fin/extrato_contas','/rel/extrato_financeiro/');
        window.open(nova_url);
    }




});



{% endblock %}